{
  "hash": "80eacdd0da989d964cd747b4708db537",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clase 01: Fundamentos de Probabilidad\"\nsubtitle: \"Estadística y Econometría\"\nauthor: \"[Fran Sofía Núñez Rebolledo](mailto:fnunezr@fen.uchile.cl)\"\ninstitute: \"UCH / INE\"\ndate: today\nformat:\n  revealjs:\n    theme: [default, ../../styles/slides-theme.scss]\n    slide-number: true\n    show-slide-number: all\n    hash-type: number\n    center: false\n    transition: fade\n    width: 1050\n    height: 700\n    margin: 0.1\n    highlight-style: github\n    code-line-numbers: false\n    fig-align: center\n    footer: \"Estadística y Econometría — Clase 01\"\n    logo: ../../figures/logos/logo-curso.png\n    chalkboard: true\n    multiplex: false\n---\n\n## Contenidos de hoy\n\n1. [¿Por qué probabilidad?](#por-qué-probabilidad)\n2. [Espacios muestrales y eventos](#espacios-muestrales)\n3. [Axiomas de probabilidad y función de probabilidad](#axiomas-de-probabilidad)\n4. [Probabilidad condicional](#probabilidad-condicional)\n5. [Independencia](#independencia)\n6. [Teorema de Bayes](#teorema-de-bayes)\n7. [Combinatoria (opcional)](#combinatoria)\n\n\n# ¿Por qué probabilidad?\n\n## La probabilidad como lenguaje de la incertidumbre\n\nLa probabilidad es un mecanismo que permite estudiar sucesos aleatorios [@canavos]. A su vez, la probabilidad es el lenguaje matemático utilizado para manejar la incertidumbre [@hansen-for-economist]. \n\n. . .\n\nPor lo tanto, la teoría de probabilidades nos da el **lenguaje formal** para cuantificar esa incertidumbre. Sin ella, no podríamos definir qué significa que un estimador sea \"bueno\", ni construir intervalos de confianza, ni evaluar hipótesis.\n\n. . .\n\nA diferencia de los eventos deterministas, gran parte de nuestro entorno natural y social está marcado por la incertidumbre. En este escenario, la probabilidad es la herramienta matemática que nos permite *cuantificar la aleatoriedad*. No elimina la incertidumbre, pero la vuelve medible, y eso es lo que después nos permitirá hacer **inferencias** y **predicciones** con un grado de confianza conocido.\n\n## Conceptos de probabilidad\n\nAunque la probabilidad es un concepto intuitivo y cotidiano — decimos \"probablemente llueva\" o \"es muy probable que el vuelo se atrase\" — no existe una única interpretación científica del término aceptada universalmente [@probability-statistics].\n\n. . .\n\nA lo largo de la historia se han propuesto distintas interpretaciones, cada una con fortalezas y limitaciones. Revisaremos las tres principales:\n\n1. Interpretación **frecuentista**\n2. Interpretación **clásica**\n3. Interpretación **subjetiva**\n\n. . .\n\n::: {.callout-important}\n## Nota clave\nLa teoría matemática de la probabilidad **no depende** de cuál interpretación se adopte. Los axiomas y resultados que usaremos en este curso son válidos bajo cualquiera de ellas [@probability-statistics].\n:::\n\n## Interpretación frecuentista\n\nLa probabilidad de un resultado se interpreta como la [frecuencia relativa]{.alert} con que ese resultado se obtendría si el proceso se repitiera muchas veces bajo condiciones similares [@probability-statistics].\n\n. . .\n\n**Ejemplo:** La probabilidad de obtener cara al lanzar una moneda es $1/2$ porque, al lanzarla un gran número de veces, la proporción de caras se aproximaría a $1/2.$\n\n. . .\n\n### Limitaciones\n\n- **Vaguedad en las condiciones:** ¿Qué es un \"gran número\" de repeticiones? ¿Qué tan \"similares\" deben ser las condiciones?\n- **No toda variación se elimina:** si lanzamos una moneda 1.000.000 de veces, no esperamos exactamente 500.000 caras, pero sí un número cercano.\n- **Solo aplica a procesos repetibles:** no puede usarse directamente para eventos únicos, como la probabilidad de que un proyecto de investigación médica tenga éxito o de que una persona específica se case en los próximos dos años.\n\n## En R: la interpretación frecuentista\n\nSimulemos 10.000 lanzamientos de una moneda justa y veamos cómo evoluciona la proporción de caras:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 10000\nlanzamientos <- sample(c(\"cara\", \"sello\"), size = n, replace = TRUE)\nprop_caras <- cumsum(lanzamientos == \"cara\") / (1:n)\n\nprop_caras[c(10, 100, 1000, 10000)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6000 0.5700 0.5060 0.5017\n```\n\n\n:::\n:::\n\n\n. . .\n\nCon pocos lanzamientos la proporción puede alejarse bastante de $1/2$; a medida que $n$ crece, se estabiliza cerca de ese valor. Esta es la intuición que formalizaremos como **ley de los grandes números** en la clase 3.\n\n## En R: la interpretación frecuentista\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nplot(prop_caras, type = \"l\",\n     log = \"x\", ylim = c(0.2, 0.8),\n     xlab = \"Lanzamientos\",\n     ylab = \"Proporción de caras\")\nabline(h = 0.5, lty = 2,\n       col = \"#69000C\")\n```\n\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-2-1.png){width=480}\n:::\n:::\n\n\n## Interpretación clásica\n\nSe basa en el concepto de [resultados igualmente probables]{.alert}. Si un proceso tiene $n$ resultados posibles y todos son igualmente verosímiles, la probabilidad de cada uno es $1/n$ [@probability-statistics].\n\n. . .\n\n**Ejemplo:** Al lanzar una moneda justa hay dos resultados igualmente probables, por lo que $P(\\text{cara}) = P(\\text{sello}) = 1/2$.\n\n. . .\n\n### Limitaciones\n\n- **Circularidad:** definir \"igualmente probables\" equivale a decir que tienen la misma probabilidad, que es justamente lo que intentamos definir.\n- **No ofrece un método sistemático** para asignar probabilidades cuando los resultados **no** son igualmente probables (e.g., ¿cuál es la probabilidad de que un proyecto de investigación sea exitoso?).\n\n## Interpretación subjetiva\n\nSegún la interpretación subjetiva o personal, la probabilidad que una persona asigna a un resultado representa su [propio juicio]{.alert} sobre la verosimilitud de que ese resultado ocurra, basado en sus creencias e información disponible [@probability-statistics].\n\n. . .\n\nDos personas con creencias o información distintas pueden asignar probabilidades diferentes al mismo evento. Por eso se habla de la **probabilidad subjetiva** de un resultado, más que de su \"probabilidad verdadera\".\n\n. . .\n\n### Limitaciones\n\n- **Consistencia:** exigir que los juicios de una persona sobre un número infinito de eventos sean perfectamente coherentes y libres de contradicciones no parece humanamente alcanzable.\n- **Falta de objetividad:** no provee una base común para que dos o más científicos lleguen a un acuerdo sobre el estado del conocimiento en su área.\n\n. . .\n\nSin embargo, si los juicios de una persona satisfacen ciertas condiciones de consistencia, se puede demostrar que sus probabilidades subjetivas quedan unívocamente determinadas [@probability-statistics].\n\n## Las tres interpretaciones en perspectiva\n\n::: {.columns}\n::: {.column width=\"33%\"}\n\n**Frecuentista**\n\n- Probabilidad = frecuencia relativa a largo plazo\n- Requiere repetibilidad\n- Base de la estadística clásica\n\n:::\n::: {.column width=\"33%\"}\n\n**Clásica**\n\n- Probabilidad = casos favorables / casos posibles\n- Requiere resultados igualmente probables\n- Útil en juegos de azar y combinatoria\n\n:::\n::: {.column width=\"34%\"}\n\n**Subjetiva**\n\n- Probabilidad = grado de creencia personal\n- Aplica a eventos únicos\n- Base de la estadística bayesiana\n\n:::\n:::\n\n. . .\n\nEn la práctica, el quehacer del/x científicx puede combinar las tres: usar frecuencias relativas de datos pasados, considerar simetrías del problema, e incorporar su propio juicio. La asignación final de probabilidades numéricas es, en última instancia, responsabilidad del/x investigador/x [@probability-statistics].\n\n# Espacios muestrales y eventos {#espacios-muestrales}\n\n## Experimentos aleatorios\n\n::: {.callout-note}\n## Definición: Experimento\nUn **experimento** es cualquier proceso, real o hipotético, cuyos resultados posibles pueden identificarse de antemano, pero cuyo resultado específico no puede predecirse con certeza [@probability-statistics].\n:::\n\n. . .\n\nLa teoría de la probabilidad se ocupa de los distintos resultados que podrían obtenerse y de los posibles eventos que podrían ocurrir cuando se realiza un experimento [@probability-statistics].\n\n. . .\n\n**Ejemplos:**\n\n- Lanzar una moneda al aire: ¿saldrá cara o sello?\n- Registrar la variación del valor de un índice bursátil: ¿subirá o bajará?\n- Seleccionar un individuo al azar y encuestarlo sobre su situación económica: ¿cuál será su ingreso por hora? [@hansen-for-economist]\n\n## Experimentos aleatorios\n\nEn todos estos casos, la falta de conocimiento previo sobre el resultado nos lleva a describir el resultado como [aleatorio]{.alert}.\n\n## Resultados y espacio muestral\n\n::: {.callout-note}\n## Definición: Resultado (*outcome*)\nUn **resultado** es un resultado específico de un experimento. Por ejemplo, en el lanzamiento de una moneda, un resultado es cara (H) o sello (T) [@hansen-for-economist].\n:::\n\n. . .\n\n::: {.callout-note}\n## Definición: Espacio muestral\nEl **espacio muestral** $\\Omega$ es el conjunto de todos los resultados posibles de un experimento [@probability-statistics; @hansen-for-economist].\n:::\n\n. . .\n\n**Ejemplos:**\n\n- Lanzar una moneda: $\\Omega = \\{H, T\\}$\n- Lanzar dos monedas en secuencia: $\\Omega = \\{HH, HT, TH, TT\\}$\n- Lanzar un dado: $\\Omega = \\{1, 2, 3, 4, 5, 6\\}$\n\n## Espacios muestrales discretos y continuos\n\nEl espacio muestral puede ser [finito]{.alert}, [infinito numerable]{.alert} o [infinito no numerable]{.alert}. De esta distinción se sigue la clasificación en espacios discretos y continuos.\n\n. . .\n\n::: {.callout-note}\n## Definición: Espacio muestral discreto\nUn espacio muestral es **discreto** si sus resultados pueden ponerse en correspondencia uno a uno con un subconjunto de los enteros positivos. Es decir, es finito o infinito numerable (*countable*) [@probability-statistics].\n:::\n\n. . .\n\n**Ejemplos:**\n\n- Finito: lanzar un dado, $\\Omega = \\{1, 2, 3, 4, 5, 6\\}$\n- Finito: respuesta a encuesta Likert, $\\Omega = \\{1, 2, 3, 4, 5\\}$\n- Infinito numerable: número de veces que un cliente visita una tienda, $\\Omega = \\{0, 1, 2, \\ldots\\}$\n\n## Espacios muestrales continuos\n\n::: {.callout-note}\n## Definición: Espacio muestral continuo\nUn espacio muestral es **continuo** si su conjunto de resultados es un intervalo (acotado o no) de números reales, es decir, un subconjunto no numerable (*uncountable*) de $\\mathbb{R}$ [@probability-statistics].\n:::\n\n. . .\n\nCuando la probabilidad se distribuye de forma continua sobre $\\Omega$, cada resultado individual $\\{\\omega\\}$ tiene probabilidad 0. Por eso no se asigna probabilidad a puntos aislados, sino a [intervalos]{.alert}. Para $a < b$:\n\n$$P([a, b]) = \\int_a^b f(x) \\, dx$$\n\ndonde $f$ es la función de densidad de probabilidad (que formalizaremos más adelante).\n\n## Espacios muestrales continuos\n\n**Ejemplo:** El ingreso mensual de un hogar tiene espacio muestral $\\Omega = [0, +\\infty)$. La probabilidad de que el ingreso caiga en un rango $[y_1, y_2]$ sería:\n\n$$P(y_1 \\leq Y \\leq y_2) = \\int_{y_1}^{y_2} f_Y(y) \\, dy$$\n\n. . .\n\nOjo: que $\\Omega$ sea continuo no garantiza que *todos* los puntos tengan probabilidad 0. Una fracción de hogares puede tener ingreso exactamente igual a 0, y ese punto sí tiene probabilidad positiva. Estas distribuciones *mixtas* son frecuentes en datos económicos.\n\n## Eventos\n\n::: {.callout-note}\n## Definición: Evento\nUn **evento** $A$ es un subconjunto bien definido del espacio muestral: $A \\subseteq \\Omega$. Representa una colección de resultados del experimento [@probability-statistics; @hansen-for-economist].\n:::\n\n. . .\n\nDecimos que el evento $A$ **ha ocurrido** si el resultado del experimento es un elemento de $A$, es decir, si $\\omega_{\\text{obs}} \\in A.$\n\n. . .\n\n**Ejemplo:** En el lanzamiento de un dado con $\\Omega = \\{1, 2, 3, 4, 5, 6\\}$:\n\n- $A$ = \"sale un número par\" = $\\{2, 4, 6\\}$\n- $B$ = \"sale un número mayor que 2\" = $\\{3, 4, 5, 6\\}$\n\nPuesto que los resultados pueden interpretarse como elementos de un conjunto y los eventos como subconjuntos, el lenguaje y los conceptos de la [teoría de conjuntos]{.alert} proporcionan el contexto natural para desarrollar la teoría de la probabilidad [@probability-statistics].\n\n## Operaciones con eventos\n\nLas operaciones de conjuntos nos permiten construir nuevos eventos a partir de eventos existentes:\n\n. . .\n\n| Operación | Notación | Significado |\n|-----------|----------|-------------|\n| Unión | $A \\cup B$ | Ocurre $A$ o $B$ (o ambos) |\n| Intersección | $A \\cap B$ | Ocurren $A$ y $B$ simultáneamente |\n| Complemento | $A^c$ | No ocurre $A$ |\n| Contención | $A \\subset B$ | Si ocurre $A$, entonces necesariamente ocurre $B$ |\n\n. . .\n\n::: {.callout-note}\n## Definición: Conjunto vacío\nEl subconjunto de $\\Omega$ que no contiene ningún elemento se llama **conjunto vacío** y se denota $\\emptyset$. En términos de eventos, representa cualquier evento que no puede ocurrir [@probability-statistics].\n:::\n\n## Eventos disjuntos\n\n::: {.callout-note}\n## Definición: Eventos disjuntos (mutuamente excluyentes)\nDos eventos $A$ y $B$ son **disjuntos** si no tienen resultados en común, es decir, si $A \\cap B = \\emptyset$. No pueden ocurrir simultáneamente.\n:::\n\n. . .\n\n**Ejemplo:** En el lanzamiento de un dado:\n\n- $A$ = \"sale menor o igual a 3\" = $\\{1, 2, 3\\}$\n- $B$ = \"sale mayor o igual a 5\" = $\\{5, 6\\}$\n- $A \\cap B = \\emptyset$ — no pueden suceder a la vez.\n\n. . .\n\nSi $A$ y $B$ son disjuntos, exactamente una de estas tres afirmaciones es verdadera:\n\n1. Ocurre $A$ (e.g., sale un 2)\n2. Ocurre $B$ (e.g., sale un 5)\n3. No ocurre ni $A$ ni $B$ (e.g., sale un 4)\n\n## Partición del espacio muestral\n\n::: {.callout-note}\n## Definición: Partición\nLos eventos $A_1, A_2, \\ldots, A_k$ forman una **partición** de $\\Omega$ si son mutuamente disjuntos y su unión es igual a $\\Omega$:\n\n$$A_i \\cap A_j = \\emptyset \\quad \\text{para } i \\neq j \\qquad \\text{y} \\qquad \\bigcup_{i=1}^{k} A_i = \\Omega$$\n:::\n\n. . .\n\n**Ejemplo:** En el lanzamiento de un dado, los eventos $A_i = \\{i\\}$ para $i = 1, \\ldots, 6$ forman una partición de $\\Omega = \\{1, 2, 3, 4, 5, 6\\}$, pues son disjuntos y cubren todos los resultados posibles.\n\n. . .\n\nEl concepto de partición será fundamental más adelante: la [ley de probabilidad total]{.alert} y el [Teorema de Bayes]{.alert} se construyen sobre la idea de descomponer $\\Omega$ en piezas disjuntas y exhaustivas.\n\n## Conjuntos finitos, numerables y no numerables\n\nEsta distinción, que parece puramente matemática, tiene consecuencias directas sobre cómo asignamos probabilidades.\n\n. . .\n\n::: {.callout-note}\n## Definición: Numerable y no numerable\nUn conjunto infinito $A$ es **numerable** (*countable*) si existe una correspondencia uno a uno entre sus elementos y los números naturales $\\{1, 2, 3, \\ldots\\}$. Un conjunto es **no numerable** (*uncountable*) si no es ni finito ni numerable [@probability-statistics].\n:::\n\n. . .\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Conjuntos numerables:**\n\n- Los enteros $\\mathbb{Z}$\n- Los números pares\n- Los primos\n- Los racionales $\\mathbb{Q}$\n\n:::\n::: {.column width=\"50%\"}\n\n**Conjuntos no numerables:**\n\n- Los reales $\\mathbb{R}$\n- El intervalo $[0, 1]$\n- Los reales positivos $\\mathbb{R}^+$\n\n:::\n:::\n\n## Conjuntos finitos, numerables y no numerables\n\nCuando $\\Omega$ es numerable, podemos asignar probabilidad a cada resultado individual. Cuando $\\Omega$ es no numerable, debemos trabajar con probabilidades sobre [intervalos]{.alert}, lo que nos llevará a las funciones de densidad.\n\n## Síntesis: el lenguaje de la probabilidad\n\n\n\n<table style=\"width:100%; font-size: 0.85em;\">\n<thead>\n<tr style=\"background-color: #69000C; color: white;\">\n<th style=\"width:50%; padding: 8px;\">Castellano</th>\n<th style=\"width:50%; padding: 8px;\">Notación de conjuntos</th>\n</tr>\n</thead>\n<tbody>\n<tr><td>Espacio muestral</td><td>$\\Omega$</td></tr>\n<tr><td>$\\omega$ es un posible resultado</td><td>$\\omega \\in \\Omega$</td></tr>\n<tr><td>$A$ es un evento</td><td>$A \\subseteq \\Omega$</td></tr>\n<tr><td>$A$ ocurrió</td><td>$\\omega_{\\text{obs}} \\in A$</td></tr>\n<tr><td>Algo debe ocurrir</td><td>$\\omega_{\\text{obs}} \\in \\Omega$</td></tr>\n<tr><td>$A$ o $B$ (o ambos)</td><td>$A \\cup B$</td></tr>\n<tr><td>$A$ y $B$</td><td>$A \\cap B$</td></tr>\n<tr><td>No $A$</td><td>$A^c$</td></tr>\n<tr><td>$A$ implica $B$</td><td>$A \\subset B$</td></tr>\n<tr><td>$A$ y $B$ son disjuntos</td><td>$A \\cap B = \\emptyset$</td></tr>\n<tr><td>$A_1, \\ldots, A_n$ partición de $\\Omega$</td><td>$A_i \\cap A_j = \\emptyset \\;\\; (i \\neq j)$ y $\\bigcup_i A_i = \\Omega$</td></tr>\n</tbody>\n</table>\n\n## Síntesis: el lenguaje de la probabilidad\n\nEsta tabla resume el puente entre el lenguaje cotidiano y la formalización matemática que usaremos de aquí en adelante. Todo lo que sigue ---axiomas, funciones de probabilidad, condicionalidad--- se construye sobre estas definiciones [@probability-statistics; @canavos; @hansen-for-economist]. Lo fundamental de entender es que esta base matemática es lo que nos entregará las herramientas para *modelar* estadísticamente fenómenos de la realidad. \n\n\n\n# Axiomas de probabilidad y función de probabilidad {#axiomas-de-probabilidad}\n\n## La función de probabilidad\n\nHasta ahora hemos descrito eventos usando teoría de conjuntos. El paso siguiente es asignarle a cada evento un [número real]{.alert} que mida la posibilidad de que ese evento ocurra cuando se realice el experimento.\n\n. . .\n\nLo que necesitamos es una función que tome eventos como argumento y devuelva probabilidades:\n\n$$\\text{Evento } A \\longrightarrow P(A) \\longrightarrow \\text{Número real}$$\n\n. . .\n\nDiremos que una función de probabilidad, por tanto, es \"una función $\\mathbb{P}$ que asigna un valor numérico a eventos\" [@hansen-for-economist, p. 2]. Esto significa que $\\mathbb{P}$ (o $\\Pr$) es una función del espacio de eventos a la recta real. Las probabilidades son, por tanto, números que miden qué tan posible es que un suceso ocurra.\n\n## Definición de función de probabilidad\n\n::: {.callout-note}\n## Definición: Función de probabilidad\nUna **medida de probabilidad**, o simplemente una **probabilidad**, sobre un espacio muestral $\\Omega$ es una especificación de números $P(A)$ para todos los eventos $A$ que satisface los tres axiomas de la probabilidad [@probability-statistics].\n:::\n\n. . .\n\nNo cualquier asignación de números a eventos constituye una función de probabilidad. Solo aquellas que satisfacen los axiomas que veremos a continuación.\n\n. . .\n\n::: {.callout-important}\nCualquier función $\\Pr$ que satisfaga los axiomas es una función de probabilidad válida. No importa cómo se hayan determinado las probabilidades ---ya sea por frecuencias, simetrías o juicio subjetivo--- mientras cumplan los axiomas, deben satisfacer también todas las propiedades que se derivan de ellos [@probability-statistics; @hansen-for-economist].\n:::\n\n## Los tres axiomas de Kolmogorov (1933)\n\nUna función de probabilidad $\\Pr$ asigna a cada evento $A$ un número real $\\Pr(A)$ que satisface:\n\n. . .\n\n**Axioma 1** (No negatividad): Para todo evento $A$,\n$$\\Pr(A) \\geq 0$$\n\n. . .\n\n**Axioma 2** (Normalización):\n$$\\Pr(\\Omega) = 1$$\n\n. . .\n\n**Axioma 3** (Aditividad numerable): Para toda secuencia infinita de eventos disjuntos $A_1, A_2, \\ldots$,\n\n$$\\Pr\\left(\\bigcup_{i=1}^{\\infty} A_i\\right) = \\sum_{i=1}^{\\infty} \\Pr(A_i)$$\n\n## Los tres axiomas de Kolmogorov (1933)\n\nDe estos tres axiomas se derivan **todas** las propiedades de la probabilidad que usaremos en el curso. En general, utilizaremos $\\Pr$ para denotar una función de probabilidad, pero en la literatura se puede ver como $P$ o $\\mathbb{P}$ también. \n\n. . .\n\nUn ensayo muy lindo sobre Kolmogorov, puede verse en [Rolando Rebolledo. “Kolmogorov y su época”. En: Revista de la Sociedad Chilena de Estadı́stica (1988).](https://www.researchgate.net/profile/Rolando-Rebolledo-2/publication/261707417_KOLMOGOROV_Y_SU_EPOCA_El_pensamiento_y_la_accion/links/02e7e5351c5b1c4db6000000/KOLMOGOROV-Y-SU-EPOCA-El-pensamiento-y-la-accion.pdf) \n\n## Interpretación de los axiomas\n\nEl **Axioma 1** dice que las probabilidades no pueden ser negativas. Esto es razonable en el siguiente sentido: si nos preguntamos cuál es la probabilidad de que nos caiga un rayo, no decimos $-99\\%,$ sino $0\\%$ si creemos que no ocurrirá. Cuando *no hay* probabilidad de un suceso, es $\\Pr(A) = 0.$ \n\n. . .\n\nEl **Axioma 2** dice que la probabilidad del espacio muestral completo es 1. Captura la idea de que el espacio muestral incluye *todos* los resultados posibles: algo tiene que ocurrir. Es esencialmente una normalización [@hansen-for-economist].\n\n. . .\n\nEl **Axioma 3** es la [propiedad aditiva]{.alert} e impone estructura considerable. Establece que si dos eventos no pueden ocurrir simultáneamente, la probabilidad de que ocurra uno u otro es la suma de sus probabilidades individuales [@hansen-for-economist]. Es decir, si $A$ y $B$ son disjuntos:\n\n$$\\Pr(A \\cup B) = \\Pr(A) + \\Pr(B)$$\n\n## Cuidado con el Axioma 3\n\n::: {.callout-important}\n## El Axioma 3 solo aplica a eventos disjuntos\nEs un error frecuente aplicar la aditividad a eventos que **no** son disjuntos.\n:::\n\n. . .\n\n**Ejemplo:** Considere el lanzamiento de dos dados. Sea $A$ = \"sale 1 en el primer dado\" y $B$ = \"sale 1 en el segundo dado\".\n\n. . .\n\nEs tentador escribir $\\Pr(\\text{1 en algun dado}) = \\Pr(A \\cup B) = \\Pr(A) + \\Pr(B), \\qquad$ pero esto es [incorrecto]{.alert} porque $A$ y $B$ no son disjuntos: el resultado \"1 en ambos dados\" pertenece tanto a $A$ como a $B$ [@hansen-for-economist].\n\n. . .\n\nLo correcto es restar la intersección: $\\Pr(A \\cup B) = \\frac{1}{6} + \\frac{1}{6} - \\frac{1}{36} = \\frac{11}{36}$, que es menor que $\\frac{12}{36}$.\n\n\n\n## Ejemplo: Funciones de probabilidad válidas e inválidas\n\nConsidere el lanzamiento de una moneda con $\\Omega = \\{H, T\\}$.\n\n. . .\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Válidas** ✓\n\n- $\\Pr(H) = 0.5, \\Pr(T) = 0.5\\quad$ (moneda justa)\n- $\\Pr(H) = 0.6, \\Pr(T) = 0.4\\quad$ (moneda cargada)\n\n:::\n::: {.column width=\"50%\"}\n\n**Inválidas** ✗\n\n- $\\Pr(H) = -0.6,  \\Pr(T) = 0.6\\quad$ (viola Axioma 1)\n- $\\Pr(H) = 0.6, \\Pr(T) = 0.6\\quad$ (viola Axioma 2: suma $\\neq 1)$\n\n:::\n:::\n\n. . .\n\nNo existe una única función de probabilidad para un experimento dado. Lo que los axiomas exigen es consistencia interna, no una asignación particular [@hansen-for-economist].\n\n## Ejemplo: Dado justo\n\nEn el lanzamiento de un dado con $\\Omega = \\{1, 2, 3, 4, 5, 6\\}, \\hspace{0.6cm}$ sea $\\Pr(A)$ el número de elementos de $A$ dividido por 6 [@probability-statistics].\n\n. . .\n\n- Axioma 1: $\\Pr(A) = |A|/6 \\geq 0\\hspace{0.6cm}  \\checkmark$ \n- Axioma 2: $\\Pr(\\Omega) = 6/6 = 1\\hspace{0.6cm} \\checkmark$ \n- Axioma 3: Si $A = \\{1, 3, 5\\}\\hspace{0.6cm}$, entonces $\\Pr(A) = p_1 + p_3 + p_5 = 3/6\\hspace{0.6cm}  \\checkmark$ \n\n. . .\n\n**¿Y un dado cargado?** Supongamos que el 6 tiene el doble de probabilidad de salir. Podemos asignar $p_i = 1/7\\hspace{0.6cm}$  para $i = 1, \\ldots, 5\\hspace{0.6cm}$  y  $p_6 = 2/7.\\hspace{0.6cm}$ Para cualquier evento $A\\hspace{0.6cm}$, definimos $\\Pr(A) = \\sum_{i \\in A} p_i.\\hspace{0.6cm}$ Esto también satisface los tres axiomas [@probability-statistics].\n\n## Ejemplos con datos reales\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Índice S&P 500**\n\nSea $U$ = \"el índice sube en una semana\" y $D$ = \"el índice baja\". El espacio muestral es $\\Omega = \\{U, D\\}\\hspace{0.6cm}$, similar a una moneda. Con datos de 3.584 semanas (1950–2017):\n\n$$\\Pr(U) = 0.57, \\quad \\Pr(D) = 0.43$$\n\nLa probabilidad de un alza es algo mayor que la de una moneda justa [@hansen-for-economist].\n\n:::\n::: {.column width=\"50%\"}\n\n**Salarios en EE.UU.**\n\nSea $H$ = \"salario > \\$25/hora\" y $L$ = \"salario $\\leq$ \\$25/hora\". Con una muestra de 50.742 trabajadores (2009):\n\n$$\\Pr(H) = 0.31, \\quad \\Pr(L) = 0.69$$\n\nAntes de encuestar a un individuo al azar, su salario es incierto y aleatorio [@hansen-for-economist].\n\n:::\n:::\n\n## Propiedades de la función de probabilidad\n\nA partir de los axiomas se demuestran las siguientes propiedades. Para cualesquiera eventos $A$ y $B$ [@probability-statistics; @hansen-for-economist]:\n\n. . .\n\n**1.** $\\Pr(A^c) = 1 - \\Pr(A)$\n\n. . .\n\n**2.** $\\Pr(\\emptyset) = 0$\n\n. . .\n\n**3.** $0 \\leq \\Pr(A) \\leq 1$\n\n. . .\n\n**4.** **Monotonía:** Si $A \\subset B\\hspace{0.6cm}$, entonces $\\Pr(A) \\leq \\Pr(B)$\n\n. . .\n\n**5.** **Inclusión-Exclusión:** $\\Pr(A \\cup B) = \\Pr(A) + \\Pr(B) - \\Pr(A \\cap B)$\n\n. . .\n\n**6.** $\\Pr(A \\cap B^c) = \\Pr(A) - \\Pr(A \\cap B)$\n\n## Demostración: $\\Pr(\\emptyset) = 0$ (opcional)\n\nConsideremos la secuencia infinita $A_1, A_2, \\ldots$ tal que $A_i = \\emptyset$ para todo $i$. Como $\\emptyset \\cap \\emptyset = \\emptyset$, los eventos son disjuntos. Además, $\\bigcup_{i=1}^{\\infty} A_i = \\emptyset$. Entonces, por el Axioma 3 [@probability-statistics]:\n\n$$\\Pr(\\emptyset) = \\Pr\\left(\\bigcup_{i=1}^{\\infty} A_i\\right) = \\sum_{i=1}^{\\infty} \\Pr(\\emptyset)$$\n\n. . .\n\nLa única forma de que un número sea igual a la suma infinita de sí mismo es que ese número sea cero. $\\blacksquare$\n\n## Demostración: $\\Pr(A^c) = 1 - \\Pr(A)$ (opcional)\n\nComo $A$ y $A^c$ son disjuntos y $A \\cup A^c = \\Omega$, por el Axioma 3 (aditividad finita, que se deriva del Axioma 3):\n\n$$\\Pr(A \\cup A^c) = \\Pr(A) + \\Pr(A^c)$$\n\n. . .\n\nY como $A \\cup A^c = \\Omega$, por el Axioma 2:\n\n$$\\Pr(\\Omega) = 1 = \\Pr(A) + \\Pr(A^c)$$\n\n. . .\n\nPor lo tanto:\n\n$$\\Pr(A^c) = 1 - \\Pr(A) \\qquad \\blacksquare$$\n\n## Demostración: Si $A \\subset B$, entonces $\\Pr(A) \\leq \\Pr(B)$ (opcional)\n\nEl evento $B$ puede descomponerse como la unión de dos eventos disjuntos: $B = A \\cup (B \\cap A^c)$.\n\n. . .\n\nPor aditividad:\n\n$$\\Pr(B) = \\Pr(A) + \\Pr(B \\cap A^c)$$\n\n. . .\n\nComo $\\Pr(B \\cap A^c) \\geq 0$ por el Axioma 1:\n\n$$\\Pr(B) \\geq \\Pr(A) \\qquad \\blacksquare$$\n\n. . .\n\nDe esta misma demostración, junto con el hecho de que $A \\subset \\Omega$ para todo evento $A$, se deduce que $\\Pr(A) \\leq \\Pr(\\Omega) = 1$. Combinando con el Axioma 1, obtenemos $0 \\leq \\Pr(A) \\leq 1$ [@probability-statistics].\n\n## Demostración: Inclusión-Exclusión (opcional)\n\nQueremos demostrar que $\\Pr(A \\cup B) = \\Pr(A) + \\Pr(B) - \\Pr(A \\cap B)$.\n\n. . .\n\nNotemos que $A \\cup B = B \\cup (A \\cap B^c)$, donde $B$ y $A \\cap B^c$ son disjuntos. Entonces:\n\n$$\\Pr(A \\cup B) = \\Pr(B) + \\Pr(A \\cap B^c)$$\n\n. . .\n\nAdemás, $A = (A \\cap B) \\cup (A \\cap B^c)$, donde ambos términos son disjuntos, por lo que:\n\n$$\\Pr(A) = \\Pr(A \\cap B) + \\Pr(A \\cap B^c) \\implies \\Pr(A \\cap B^c) = \\Pr(A) - \\Pr(A \\cap B)$$\n\n. . .\n\nSustituyendo:\n\n$$\\Pr(A \\cup B) = \\Pr(B) + \\Pr(A) - \\Pr(A \\cap B) \\qquad \\blacksquare$$\n\n## Propiedades adicionales: desigualdades útiles (opcional)\n\n::: {.callout-note}\n## Desigualdad de Boole\nPara cualesquiera eventos $A_1, \\ldots, A_n:$\n$$\\Pr\\left(\\bigcup_{i=1}^{n} A_i\\right) \\leq \\sum_{i=1}^{n} \\Pr(A_i)$$\n\nLa probabilidad de una unión está acotada superiormente por la suma de las probabilidades individuales [@hansen-for-economist].\n:::\n\n. . .\n\n::: {.callout-note}\n## Desigualdad de Bonferroni\nPara cualesquiera eventos $A_1, \\ldots, A_n:$\n$$\\Pr\\left(\\bigcap_{i=1}^{n} A_i\\right) \\geq 1 - \\sum_{i=1}^{n} \\Pr(A_i^c)$$\n\nLa probabilidad de una intersección está acotada inferiormente [@probability-statistics; @hansen-for-economist].\n:::\n\n## Propiedades adicionales: desigualdades útiles (opcional)\n\nAmbas desigualdades (de Boole y de Bonferroni) son utilizadas frecuentemente en cálculos de probabilidad y serán útiles cuando veamos intervalos de confianza simultáneos.\n\n## Probabilidad cero $\\neq$ imposibilidad\n\n::: {.callout-important}\n## Nota clave\nCuando un evento tiene probabilidad 0, eso **no** significa que el evento sea imposible [@probability-statistics].\n:::\n\n. . .\n\nEn un espacio muestral continuo, hay muchos eventos con probabilidad 0 que no son todos imposibles. Por ejemplo, si la demanda de agua puede tomar cualquier valor en $[4, 200],\\hspace{0.2cm}$ el evento \"la demanda es exactamente 150\" corresponde a un solo punto ---que tiene área 0--- y por tanto probabilidad 0. Pero la demanda [*podría*]{.alert} ser 150 [@probability-statistics].  \n\n## Probabilidad cero $\\neq$ imposibilidad\n\nUn evento con probabilidad 0 o 1 se denomina [trivial]{.alert} [@hansen-for-economist].\n\n. . .\n\n**Ejemplo:** en el lanzamiento de una moneda, usualmente definimos $\\Omega = \\{H, T\\}.$ Pero podríamos ser más exhaustivos y considerar $\\Omega = \\{H, T, \\text{canto}, \\text{desaparece}\\}$, donde \"canto\" significa que la moneda queda parada sobre su borde y \"desaparece\" que se pierde (cae por una rejilla, por ejemplo). Ambos resultados son físicamente concebibles, pero les asignamos $\\Pr(\\text{canto}) = 0$ y $\\Pr(\\text{desaparece}) = 0$. Son eventos triviales: no son imposibles en principio, pero no contribuyen al comportamiento aleatorio del experimento. En la práctica, los ignoramos y trabajamos con $\\Omega = \\{H, T\\}$.\n\n# Probabilidad condicional {#probabilidad-condicional}\n\n## ¿Por qué probabilidad condicional?\n\nUn uso fundamental de la probabilidad en inferencia estadística es la [actualización de probabilidades]{.alert} cuando se observan ciertos eventos. La probabilidad actualizada de un evento $A$ después de saber que el evento $B$ ha ocurrido es la probabilidad condicional de $A$ dado $B$ [@probability-statistics].\n\n. . .\n\nPreguntas como las siguientes son preguntas de probabilidad condicional:\n\n- ¿Es más probable tener un salario alto entre quienes tienen título universitario?\n- ¿Es más frecuente un alza de precios en los períodos posteriores a un aumento de aranceles?\n- ¿Es menor la tasa de recaída entre quienes recibieron un tratamiento médico?\n\n. . .\n\nTodas comparten la misma estructura: ¿cómo cambia la probabilidad de $A$ cuando sabemos que $B$ ha ocurrido?\n\n::: {.callout-warning}\nHansen (2022) plantea estas preguntas como \"¿*afecta* asistir a la universidad…?\". Aquí las reformulamos a propósito: son preguntas de **asociación**, no de causalidad. Saber que $\\Pr(A|B) \\neq \\Pr(A)$ no nos dice que $B$ *cause* $A$. Esa distinción es el tema central de la última unidad del curso.\n:::\n\n## Definición\n\n::: {.callout-note}\n## Definición: Probabilidad condicional\nSupongamos que sabemos que el evento $B$ ha ocurrido y queremos calcular la probabilidad de otro evento $A$ considerando esta información. La nueva probabilidad de $A$ se llama la **probabilidad condicional de $A$ dado $B$** y se denota $\\Pr(A|B).\\hspace{0.2cm}$ Si $\\Pr(B) > 0:$ \n\n$$\\Pr(A|B) = \\frac{\\Pr(A \\cap B)}{\\Pr(B)}$$\n\nLa probabilidad condicional no está definida si $\\Pr(B) = 0 \\hspace{0.3cm}$ [@probability-statistics].\n:::\n\n. . .\n\nLa notación \"$A \\mid B\\hspace{0.4cm}$\" se lee como \"$A$ dado $B\\hspace{0.4cm}$\" o \"$A$ asumiendo que $B$ es verdadero\". Para mayor claridad, a veces llamaremos a $\\Pr(A)\\hspace{0.2cm}$ la **probabilidad incondicional** para distinguirla de $\\Pr(A|B) \\hspace{0.3cm}$ [@probability-statistics].\n\n## Interpretación\n\nCondicionar en $B$ equivale a [restringir el espacio muestral]{.alert} a $B$. Si sabemos que $B$ ha ocurrido, entonces el resultado del experimento es necesariamente un elemento de $B$. Para evaluar la probabilidad de $A$, debemos considerar solo aquellos resultados de $B$ que también pertenecen a $A.\\hspace{0.1cm}$ Es decir, el conjunto $A \\cap B\\hspace{0.2cm}$  [@probability-statistics].\n\n. . .\n\nIntuitivamente, $\\Pr(A|B) \\hspace{0.1cm}$ mide qué proporción de la probabilidad total de $B$ está ocupada por $A:$\n\n$$\\Pr(A|B) = \\frac{\\Pr(A \\cap B)}{\\Pr(B)} = \\frac{\\text{proporción de } B \\text{ que tambien es } A}{\\text{probabilidad total de } B}$$\n\n## Ejemplo: Educación y salarios\n\nConsidere una población donde definimos los eventos $H$ = \"salario alto (> \\$25/hr)\" $\\hspace{0.6cm}$ y $C$ = \"tiene educación universitaria\". Con datos de EE.UU. [@hansen-for-economist]: $\\hspace{0.6cm}$\n\n. . .\n\n$$\\Pr(H | C) = \\frac{\\Pr(H \\cap C)}{\\Pr(C)} = \\frac{0.19}{0.36} = 0.53$$\n\n. . .\n\n$$\\Pr(H | N) = \\frac{\\Pr(H \\cap N)}{\\Pr(N)} = \\frac{0.12}{0.64} = 0.19$$\n\ndonde $N = C^c$ $\\hspace{0.6cm}$ (no tiene título universitario).\n\n. . .\n\nHay una diferencia considerable: la probabilidad condicional de obtener un salario alto es del 53% para quienes tienen título universitario, versus 19% para quienes no lo tienen. Esta brecha describe una [asociación]{.alert} entre educación y salarios que logramos medir solo con probabilidades. No nos dice cuánto de la brecha se debe a la educación misma y cuánto a otras diferencias entre ambos grupos.\n\n## Ejemplo: Ensayo clínico\n\nEn un estudio sobre recaídas en pacientes con depresión, 150 pacientes fueron asignados a cuatro grupos [@probability-statistics]:\n\n. . .\n\n| | Imipramina | Litio | Combinación | Placebo | Total |\n|---|---|---|---|---|---|\n| Recaída | 18 | 13 | 22 | 24 | 77 |\n| Sin recaída | 22 | 25 | 16 | 10 | 73 |\n| Total | 40 | 38 | 38 | 34 | 150 |\n\n. . .\n\nSea $A$ = \"recaída\" y $B$ = \"recibió placebo\". Entonces: \n\n$$\\Pr(A|B) = \\frac{24/150}{34/150} = \\frac{24}{34} = 0.706$$\n\n. . .\n\nSi en cambio el paciente recibió litio $(C):$  $\\Pr(A|C) = 13/38 = 0.342. \\hspace{0.8cm}$ El tratamiento recibido parece hacer una diferencia en la probabilidad de recaída. Cuantificar *cuánta* diferencia es exactamente lo que hacen los métodos econométricos de evaluación de impacto.\n\n## Probabilidad conjunta, marginal y condicional\n\nAl trabajar con dos eventos simultáneamente aparecen tres tipos de probabilidad que conviene distinguir con precisión:\n\n. . .\n\n**1. Probabilidad conjunta:**  la probabilidad de que $A$ y $B$ ocurran simultáneamente.\n$$\\Pr(A \\cap B)$$\n\n. . .\n\n**2. Probabilidad marginal:** la probabilidad de $A$ sin considerar $B$ (o viceversa).\n$$\\Pr(A) = \\sum_{j} \\Pr(A \\cap B_j)$$\n\n. . .\n\n**3. Probabilidad condicional:**  la probabilidad de $A$ dado que $B$ ha ocurrido.\n$$\\Pr(A|B) = \\frac{\\Pr(A \\cap B)}{\\Pr(B)}, \\quad \\Pr(B) > 0$$\n\n## Ejemplo: Tabla de contingencia\n\nSupongamos que queremos estudiar la probabilidad de que hombres y mujeres voten a la izquierda, con los siguientes datos:\n\n. . .\n\n| | Hombre $(B_1)$ | Mujer $(B_2)$ | Total |\n|---|---|---|---|\n| Vota izquierda $(A_1)$ | 30 | 20 | 50 |\n| No vota izquierda $(A_2)$ | 40 | 10 | 50 |\n| Total | 70 | 30 | 100 |\n\n. . .\n\n**Conjunta:**  $\\Pr(A_1 \\cap B_2) = 20/100 = 0.20$\n\n. . .\n\n**Marginal:**  $\\Pr(A_1) = 50/100 = 0.50$\n\n. . .\n\n**Condicional:** $\\Pr(A_1 | B_2) = \\frac{\\Pr(A_1 \\cap B_2)}{\\Pr(B_2)} = \\frac{0.20}{0.30} = 0.667$\n\nEl 66.7% de las mujeres votan a la izquierda, versus el 42.9% de los hombres $(\\Pr(A_1|B_1) = 30/70)$.\n\n## Regla de la multiplicación\n\nDe la definición de probabilidad condicional se obtiene directamente la **regla de la multiplicación** [@probability-statistics]: \n\n. . .\n\n$$\\Pr(A \\cap B) = \\Pr(B) \\cdot \\Pr(A|B) = \\Pr(A) \\cdot \\Pr(B|A)$$\n\n. . .\n\nEsta regla es útil cuando la probabilidad condicional es fácil de evaluar directamente. Por ejemplo, si extraemos dos bolas de una caja con $r$ rojas y $b$ azules **sin reposición**: la probabilidad de que la primera sea roja $(A)$ y la segunda azul $(B)$ es [@probability-statistics]: \n\n$$\\Pr(A \\cap B) = \\Pr(A) \\cdot \\Pr(B|A) = \\frac{r}{r+b} \\cdot \\frac{b}{r+b-1}$$\n\n## Regla de la multiplicación: extensión\n\nLa regla se extiende a cualquier número finito de eventos. Para $n$ eventos tales que $\\Pr(A_1 \\cap \\cdots \\cap A_{n-1}) > 0$ $\\hspace{0.6cm}$ [@probability-statistics]:\n\n$$\\Pr(A_1 \\cap A_2 \\cap \\cdots \\cap A_n) = \\Pr(A_1) \\cdot \\Pr(A_2|A_1) \\cdot \\Pr(A_3|A_1 \\cap A_2) \\cdots \\Pr(A_n | A_1 \\cap \\cdots \\cap A_{n-1})$$\n\n. . .\n\nEsta factorización es la base de la [factorización de verosimilitudes]{.alert} que usaremos cuando estudiemos estimación por máxima verosimilitud (MLE).\n\n## Las probabilidades condicionales se comportan como probabilidades\n\n::: {.callout-important}\n## Resultado clave\nTodos los resultados que se pueden demostrar para probabilidades incondicionales tienen una versión condicional dado un evento $B$ con $\\Pr(B) > 0.\\hspace{0.3cm}$  Basta reemplazar *todas* las probabilidades por probabilidades condicionales dado $B \\hspace{0.1cm}$ [@probability-statistics].\n:::\n\n. . .\n\nPor ejemplo:\n\n- $\\Pr(A^c) = 1 - \\Pr(A) \\hspace{0.6cm} \\longrightarrow \\hspace{0.6cm} \\Pr(A^c | B) = 1 - \\Pr(A|B)$\n\n- $\\Pr(A \\cup C) = \\Pr(A) + \\Pr(C) - \\Pr(A \\cap C) \\hspace{0.3cm} \\longrightarrow$\n\n$$\\Pr(A \\cup C | B) = \\Pr(A|B) + \\Pr(C|B) - \\Pr(A \\cap C | B)$$\n\n## Ley de probabilidad total\n\nSi $B_1, B_2, \\ldots, B_k\\hspace{0.5cm}$  forman una **partición** de $\\Omega$  (disjuntos y exhaustivos) con $\\Pr(B_j) > 0\\hspace{0.5cm}$ para todo $j$,  entonces para cualquier evento $A\\hspace{0.1cm}$  [@probability-statistics]:\n\n$$\\Pr(A) = \\sum_{j=1}^{k} \\Pr(B_j) \\cdot \\Pr(A|B_j)$$\n\n. . .\n\nLa ley de probabilidad total \"descompone\" la probabilidad de un evento complejo en piezas más manejables, usando una partición que reduce la incertidumbre del problema [@probability-statistics].\n\n## Ley de probabilidad total: ejemplo\n\n**Ejemplo:** ¿Cuál es la probabilidad de estar desempleado?\n\nTomemos como experimento seleccionar al azar a una persona de la fuerza de trabajo:\n\n$$\\Pr(\\text{desempleo}) = \\sum_{j=1}^{J} \\Pr(\\text{región}_j) \\cdot \\Pr(\\text{desempleo} \\mid \\text{región}_j)$$\n\nSi conocemos la tasa de desempleo de cada región y la proporción de la **fuerza de trabajo** que vive en cada una, podemos calcular la tasa de desempleo nacional. Las regiones forman una partición, y la tasa nacional es un promedio ponderado de las tasas regionales.\n\n## ¿Por qué importa la condicionalidad en econometría?\n\nLa probabilidad condicional es el [fundamento matemático]{.alert} de los modelos de regresión y de la inferencia causal.\n\n. . .\n\nLa **función de regresión poblacional** *es* una esperanza condicional:\n\n$$E[Y_i | X_i] = \\mu(X_i)$$\n\nCuando estimamos una regresión, estamos estimando cómo cambia el valor esperado de $Y$ al condicionar en distintos valores de $X.\\hspace{0.1cm}$ Si $X$ incluye varias variables, podemos comparar unidades que difieren en una de ellas y son iguales en las demás, que es la idea del [*ceteris paribus*]{.alert}.\n\n## ¿Por qué importa la condicionalidad en econometría?\n\nEn **inferencia causal**, el desafío es que condicionar en $X$ no es lo mismo que *intervenir* sobre $X. \\hspace{0.1cm}$  Los supuestos de identificación (independencia condicional, variables instrumentales, etc.) buscan garantizar que la comparación que estimamos capture un efecto causal y no solo una asociación.\n\n. . .\n\nEn **series de tiempo**, los modelos de pronóstico son modelos de media condicional: $E[Y_t | Y_{t-1}, Y_{t-2}, \\ldots] \\hspace{0.6cm}$  usa toda la historia pasada como información condicionante para proyectar el futuro.\n\n# Independencia {#independencia}\n\n## ¿Qué significa que dos eventos sean independientes?\n\nDecimos que dos eventos son **independientes** si su ocurrencia no está relacionada, o equivalentemente, si el conocimiento de que uno ocurrió no afecta la probabilidad del otro [@hansen-for-economist].\n\n. . .\n\nConsidere dos lanzamientos de moneda. Si no hay mecanismo que conecte ambos lanzamientos, esperamos que ninguno afecte al resultado del otro. De modo similar, la tasa de criminalidad en Londres y el precio del té en Shanghai no tienen razón para afectarse mutuamente [@hansen-for-economist].\n\n. . .\n\nEsta intuición implica que si $A$ y $B$ son independientes, entonces $\\Pr(A|B) = \\Pr(A)\\hspace{0.2cm}$ y $\\Pr(B|A) = \\Pr(B).\\hspace{0.2cm}$ Desde la definición de probabilidad condicional, esto implica $\\Pr(A \\cap B) = \\Pr(A)\\Pr(B).\\hspace{0.2cm}$ Usamos esta última expresión como definición formal.\n\n## Definición formal\n\n::: {.callout-note}\n## Definición: Independencia\nDos eventos $A$ y $B$ son **independientes** si y solo si:\n\n$$\\Pr(A \\cap B) = \\Pr(A) \\cdot \\Pr(B)$$\n\nEquivalentemente, si $\\Pr(A) > 0\\hspace{0.2cm}$ y $\\Pr(B) > 0:$\n\n$$\\Pr(A|B) = \\Pr(A) \\qquad \\text{y} \\qquad \\Pr(B|A) = \\Pr(B)$$\n\nSi dos eventos no son independientes, decimos que son **dependientes** [@probability-statistics; @hansen-for-economist].\n:::\n\n. . .\n\nSi dos eventos son considerados independientes porque son físicamente no relacionados, y si conocemos $\\Pr(A)\\hspace{0.2cm}$ y $\\Pr(B),\\hspace{0.2cm}$ podemos usar la definición para asignar un valor a $\\Pr(A \\cap B)\\hspace{0.2cm}$ directamente [@probability-statistics].\n\n## Independencia $\\neq$ mutua exclusividad\n\n::: {.callout-important}\n## Distinción crucial\nIndependencia y mutua exclusividad son conceptos [distintos]{.alert}, y es un error frecuente confundirlos.\n:::\n\n. . .\n\nSi $A$ y $B$ son disjuntos (mutuamente excluyentes), entonces $A \\cap B = \\emptyset,\\hspace{0.2cm}$ y por tanto:\n\n$$\\Pr(A \\cap B) = \\Pr(\\emptyset) = 0 \\neq \\Pr(A)\\Pr(B)$$\n\nsiempre que ambos tengan probabilidad positiva. Es decir, eventos disjuntos con probabilidad positiva son necesariamente [dependientes]{.alert}: saber que ocurrió $A$ te dice con certeza que $B$ no ocurrió [@hansen-for-economist; @probability-statistics].\n\n. . .\n\nDe hecho, la única forma de que eventos sean simultáneamente disjuntos e independientes es que al menos uno de ellos tenga probabilidad 0 [@probability-statistics].\n\n## Ejemplo: S&P 500 e independencia temporal\n\nRetomemos el ejemplo del S&P 500. Sea $U_t\\hspace{0.1cm}$ = \"el índice sube en la semana $t\\hspace{0.1cm}$\" [@hansen-for-economist]:\n\n. . .\n\n$$\\Pr(U_t | U_{t-1}) = \\frac{0.322}{0.567} = 0.568$$\n\n$$\\Pr(U_t | D_{t-1}) = \\frac{0.245}{0.433} = 0.566$$\n\n. . .\n\nLas dos probabilidades condicionales son prácticamente idénticas ($\\approx 0.57$). La probabilidad de un alza en una semana dada no se ve afectada por lo que ocurrió la semana anterior. Los datos son consistentes con que $U_t\\hspace{0.2cm}$ y $U_{t-1}\\hspace{0.2cm}$ sean (aproximadamente) independientes.\n\n## Ejemplo: Salarios y educación (dependencia)\n\nAhora veamos un caso de [dependencia]{.alert}. Si salarios y educación fueran independientes, las probabilidades conjuntas serían el producto de las marginales [@hansen-for-economist]:\n\n. . .\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Si fueran independientes:**\n\n| | $C$ | $N$ |\n|---|---|---|\n| $H$ | 0.11 | 0.20 |\n| $L$ | 0.25 | 0.44 |\n\n:::\n::: {.column width=\"50%\"}\n\n**Datos reales:**\n\n| | $C$ | $N$ |\n|---|---|---|\n| $H$ | 0.19 | 0.12 |\n| $L$ | 0.17 | 0.52 |\n\n:::\n:::\n\n. . .\n\nLos eventos $H \\cap C\\hspace{0.2cm}$ y $L \\cap N\\hspace{0.2cm}$ ocurren con mucha más frecuencia de lo que predeciría la independencia. Salarios y educación son **dependientes**: saber si alguien tiene título universitario cambia la probabilidad de que tenga un salario alto. Ojo, esto no demuestra que la educación *cause* salarios más altos.\n\n## Independencia de complementos\n\n::: {.callout-note}\n## Teorema\nSi $A$ y $B$ son independientes, entonces también son independientes los pares $A$ y $B^c;\\hspace{0.2cm}$ $A^c$ y $B;\\hspace{0.2cm}$ y $A^c$ y $B^c\\hspace{0.2cm}$ [@probability-statistics].\n:::\n\n. . .\n\n*Demostración (para $A$ y $B^c$):*\n\n$$\\Pr(A \\cap B^c) = \\Pr(A) - \\Pr(A \\cap B) = \\Pr(A) - \\Pr(A)\\Pr(B) = \\Pr(A)[1 - \\Pr(B)] = \\Pr(A)\\Pr(B^c) \\quad \\blacksquare$$\n\n. . .\n\nEsto es razonable: si la ocurrencia de $B$ no afecta a $A,\\hspace{0.2cm}$ tampoco debería hacerlo la no-ocurrencia de $B.$\n\n## Independencia de más de dos eventos\n\nLa definición se extiende a $k$ eventos, pero requiere más que independencia de a pares [@probability-statistics]:\n\n. . .\n\n::: {.callout-note}\n## Definición: Independencia mutua\nLos $k$ eventos $A_1, \\ldots, A_k\\hspace{0.2cm}$ son **(mutuamente) independientes** si para todo subconjunto $A_{i_1}, \\ldots, A_{i_j}\\hspace{0.2cm}$ de $j$ de estos eventos ($j = 2, 3, \\ldots, k$):\n\n$$\\Pr(A_{i_1} \\cap \\cdots \\cap A_{i_j}) = \\Pr(A_{i_1}) \\cdots \\Pr(A_{i_j})$$\n:::\n\n. . .\n\nPara tres eventos $A, B, C,\\hspace{0.2cm}$ se necesitan **cuatro** condiciones:\n\n$$\\Pr(A \\cap B) = \\Pr(A)\\Pr(B), \\quad \\Pr(A \\cap C) = \\Pr(A)\\Pr(C), \\quad \\Pr(B \\cap C) = \\Pr(B)\\Pr(C)$$\n\n$$\\text{y además: } \\quad \\Pr(A \\cap B \\cap C) = \\Pr(A)\\Pr(B)\\Pr(C)$$\n\nLa independencia de a pares **no basta** para garantizar la última condición.\n\n## Independencia condicional\n\n::: {.callout-note}\n## Definición: Independencia condicional\nLos eventos $A_1, \\ldots, A_k\\hspace{0.2cm}$ son **condicionalmente independientes dado $B$** si, para todo subconjunto $A_{i_1}, \\ldots, A_{i_j}\\hspace{0.2cm}$ de $j$ de estos eventos ($j = 2, \\ldots, k$):\n\n$$\\Pr\\left(A_{i_1} \\cap \\cdots \\cap A_{i_j} \\mid B\\right) = \\Pr(A_{i_1}|B) \\cdots \\Pr(A_{i_j}|B)$$\n:::\n\n. . .\n\nEs la misma definición de independencia mutua, pero con *todas* las probabilidades condicionadas en $B.\\hspace{0.2cm}$ Nótese que independencia condicional dado $B$ **no implica** independencia condicional dado $B^c,\\hspace{0.2cm}$ ni viceversa [@probability-statistics].\n\n## ¿Por qué importa la independencia en econometría?\n\nEl supuesto de independencia (o sus versiones más débiles) aparece en toda la econometría:\n\n. . .\n\n- **Muestreo aleatorio:** las observaciones $(X_i, Y_i)\\hspace{0.2cm}$ son i.i.d. (independientes e idénticamente distribuidas).\n\n. . .\n\n- **Exogeneidad:** $E[\\varepsilon_i | X_i] = 0,\\hspace{0.2cm}$ que es una forma de *independencia en media* entre el error y los regresores (más débil que la independencia completa).\n\n. . .\n\n- **Identificación causal:** la asignación al tratamiento es independiente de los resultados potenciales: $(Y_0, Y_1) \\perp\\!\\!\\!\\perp D.$\n\n. . .\n\nCuando estos supuestos fallan, los estimadores estándar pierden sus buenas propiedades. Gran parte de la econometría avanzada consiste en **lidiar con la falta de independencia**.\n\n# Teorema de Bayes {#teorema-de-bayes}\n\n## Teorema de Bayes\n\nUna vez que conocemos la probabilidad condicional y la ley de probabilidad total, el Teorema de Bayes se sigue directamente. Permite [invertir condicionales]{.alert}: si conocemos $\\Pr(A|B),\\hspace{0.2cm}$ podemos obtener $\\Pr(B|A).$\n\n. . .\n\n::: {.callout-important}\n## Teorema de Bayes\nSi $B_1, \\ldots, B_k\\hspace{0.2cm}$ forman una partición de $\\Omega\\hspace{0.2cm}$ con $\\Pr(B_j) > 0\\hspace{0.2cm}$ para todo $j,\\hspace{0.2cm}$ entonces:\n\n$$\\Pr(B_i|A) = \\frac{\\Pr(A|B_i) \\cdot \\Pr(B_i)}{\\sum_{j=1}^{k} \\Pr(A|B_j) \\cdot \\Pr(B_j)}$$\n:::\n\n## Teorema de Bayes (terminología)\n\n**Terminología:**\n\n| Término | Significado |\n|---------|-------------|\n| $\\Pr(B_i)\\hspace{0.2cm}$ | **Prior** — creencia antes de observar datos |\n| $\\Pr(A \\mid B_i)\\hspace{0.2cm}$ | **Verosimilitud** — probabilidad de los datos dado el parámetro |\n| $\\Pr(B_i \\mid A)\\hspace{0.2cm}$ | **Posterior** — creencia actualizada tras observar datos |\n\n## Ejemplo: diagnóstico y falsos positivos\n\nUn test diagnóstico tiene sensibilidad del 95% y especificidad del 90%. La prevalencia de la enfermedad es del 1%.\n\n. . .\n\n$$\\Pr(\\text{enfermo} \\mid \\text{test}+) = \\frac{0.95 \\times 0.01}{0.95 \\times 0.01 + 0.10 \\times 0.99}$$\n\n. . .\n\n$$= \\frac{0.0095}{0.0095 + 0.099} = \\frac{0.0095}{0.1085} \\approx 0.088$$\n\n. . .\n\n::: {.callout-important}\nAun con un test \"bueno\", un resultado positivo solo implica un **8.8%** de probabilidad de estar enfermo cuando la prevalencia es baja. Este resultado es contraintuitivo y tiene profundas implicancias para política pública.\n:::\n\n## Bayes con frecuencias naturales\n\nEl mismo cálculo se entiende mejor si pensamos en **10.000 personas**:\n\n. . .\n\n| | Test $+$ | Test $-$ | Total |\n|---|---|---|---|\n| Enfermas (1%) | 95 | 5 | 100 |\n| Sanas (99%) | 990 | 8.910 | 9.900 |\n| Total | 1.085 | 8.915 | 10.000 |\n\n. . .\n\nDe las 1.085 personas con test positivo, solo 95 están enfermas: $95 / 1.085 \\approx 0.088$. Los falsos positivos son muchos más porque, aunque el test se equivoque poco con cada persona sana, hay muchísimas más personas sanas que enfermas.\n\n## En R: verificando Bayes por simulación\n\nSimulamos una población de 100.000 personas con las mismas características:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 100000\nenfermo  <- runif(n) < 0.01                  # prevalencia de 1%\npositivo <- ifelse(enfermo,\n                   runif(n) < 0.95,          # sensibilidad: 95%\n                   runif(n) < 0.10)          # falsos positivos: 10%\n\nmean(enfermo[positivo])                      # Pr(enfermo | test +)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08419785\n```\n\n\n:::\n:::\n\n\n. . .\n\nLa proporción de enfermos entre quienes dieron positivo se acerca al $0.088$ que obtuvimos con el teorema de Bayes.\n\n# Combinatoria (opcional) {#combinatoria}\n\n## Reglas de conteo, permutaciones y combinaciones\n\nPara algunos cálculos de probabilidad es útil contar el número de resultados posibles. Tres herramientas básicas son la regla de conteo, las permutaciones y las combinaciones [@hansen-for-economist].\n\n. . .\n\n::: {.callout-note}\n## Regla de conteo\nSi una tarea consta de $K$ etapas, y la $k$-ésima etapa puede realizarse de $n_k\\hspace{0.2cm}$ formas, entonces el número total de formas de completar la tarea es $n_1 \\cdot n_2 \\cdots n_K.$\n:::\n\n. . .\n\n**Ejemplo:** si tienes 10 camisas, 3 pantalones, 5 pares de calcetines, 4 chaquetas y 2 sombreros, puedes armar $10 \\times 3 \\times 5 \\times 4 \\times 2 = 1200\\hspace{0.2cm}$ outfits distintos [@hansen-for-economist].\n\n## Permutaciones\n\n::: {.callout-note}\n## Definición: Permutación\nUna **permutación** es un reordenamiento de objetos donde el orden importa. El número de permutaciones de $N$ objetos tomados de $K$ en $K$ es [@hansen-for-economist]:\n\n$$P(N, K) = \\frac{N!}{(N-K)!}$$\n\nEn particular, el número de formas de ordenar $N$ objetos es $N!$\n:::\n\n. . .\n\n**Ejemplo:** ¿de cuántas formas se puede seleccionar un equipo ordenado de 5 estudiantes de una clase de 30?\n\n$$P(30, 5) = \\frac{30!}{25!} = 30 \\times 29 \\times 28 \\times 27 \\times 26 = 17.100.720$$\n\n## Combinaciones\n\n::: {.callout-note}\n## Definición: Combinación\nUna **combinación** es un grupo no ordenado de objetos. El número de combinaciones de $N$ objetos tomados de $K$ en $K$ es [@hansen-for-economist]:\n\n$$\\binom{N}{K} = \\frac{N!}{K!(N-K)!}$$\n\nEl símbolo $\\binom{N}{K}\\hspace{0.2cm}$ se lee \"$N$ en $K$\" o \"$N$ choose $K$\" y también se conoce como **coeficiente binomial**.\n:::\n\n. . .\n\n**Ejemplo:** ¿cuántos equipos (sin orden) de 5 estudiantes se pueden formar de una clase de 30?\n\n$$\\binom{30}{5} = \\frac{30!}{5! \\cdot 25!} = 142.506$$\n\n## Muestreo con y sin reposición\n\nLa distinción entre muestreo con y sin reposición determina qué fórmula de conteo usar [@hansen-for-economist]:\n\n. . .\n\n<table style=\"width:100%; font-size: 0.85em;\">\n<thead>\n<tr style=\"background-color: #69000C; color: white;\">\n<th style=\"width:34%; padding: 8px;\"></th>\n<th style=\"width:33%; padding: 8px;\">Sin reposición</th>\n<th style=\"width:33%; padding: 8px;\">Con reposición</th>\n</tr>\n</thead>\n<tbody>\n<tr><td><strong>Ordenado</strong></td><td>$\\frac{N!}{(N-K)!}$</td><td>$N^K$</td></tr>\n<tr><td><strong>No ordenado</strong></td><td>$\\binom{N}{K}$</td><td>$\\binom{N+K-1}{K}$</td></tr>\n</tbody>\n</table>\n\n. . .\n\nEstas herramientas deben entenderse, no memorizarse: se pueden consultar cuando se necesiten [@hansen-for-economist]. Las usaremos cuando trabajemos con la distribución binomial y con problemas de muestreo.\n\n## Resumen de la clase\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Conceptos clave:**\n\n- Interpretaciones de la probabilidad\n- Espacio muestral $\\Omega$ y eventos\n- Axiomas de Kolmogorov\n- Función de probabilidad\n- Probabilidad condicional\n- Independencia estadística\n- Teorema de Bayes\n\n:::\n::: {.column width=\"50%\"}\n\n**Próxima clase:**\n\n- Variables aleatorias discretas y continuas\n- Función de masa de probabilidad (PMF)\n- Función de densidad (PDF)\n- Función de distribución acumulada (CDF)\n- Esperanza y varianza\n\n:::\n:::\n\n## Para revisar\n\n::: {.callout-tip}\n## Lecturas sugeridas\n- DeGroot & Schervish, Capítulos 1 y 2.\n- Hansen, *Probability and Statistics for Economists*, Capítulo 1.\n- Canavos, *Probabilidad y Estadística*, Capítulo 2.\n:::\n",
    "supporting": [
      "slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}