{
  "hash": "c4069504a7b9eff0d9bc55701d62e12c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clase 02: Variables Aleatorias y Distribuciones\"\nsubtitle: \"Estadística y Econometría\"\nauthor: \"[Fran Sofía Núñez Rebolledo](mailto:fnunezr@fen.uchile.cl)\"\ninstitute: \"UCH / INE\"\ndate: today\nformat:\n  revealjs:\n    theme: [default, ../../styles/slides-theme.scss]\n    slide-number: true\n    show-slide-number: all\n    hash-type: number\n    center: false\n    transition: fade\n    width: 1050\n    height: 700\n    margin: 0.1\n    highlight-style: atom-one\n    code-line-numbers: false\n    fig-align: center\n    footer: \"Estadística y Econometría — Clase 02\"\n    logo: ../../figures/logos/logo-curso.png\n    chalkboard: true\n---\n\n\n\n## Contenidos de hoy\n\n1. [Variables aleatorias](#variables-aleatorias)\n2. [Variables aleatorias discretas](#discretas)\n3. [Función de distribución](#cdf)\n4. [Variables aleatorias continuas y densidades](#continuas)\n5. [Transformaciones](#transformaciones)\n6. [Esperanza](#esperanza)\n7. [Varianza y momentos](#varianza)\n8. [Distribuciones paramétricas](#parametricas)\n9. [Dos variables aleatorias](#bivariadas)\n\n# Variables aleatorias {#variables-aleatorias}\n\n## De resultados a números\n\nEn la clase anterior trabajamos con **eventos**: subconjuntos del espacio muestral $\\Omega$. En la práctica, casi siempre conviene representar los resultados aleatorios con [números]{.alert} [@hansen-for-economist].\n\n. . .\n\n**Ejemplo:** al lanzar una moneda, en vez de hablar de $\\{H\\}$ y $\\{T\\}$ definimos\n\n$$X = \\begin{cases} 1 & \\text{si sale cara} \\\\ 0 & \\text{si sale sello} \\end{cases}$$\n\n$X$ es aleatoria porque su valor depende del resultado del lanzamiento.\n\n. . .\n\nLo mismo hacemos con datos económicos: el ingreso de un hogar, los años de educación de una persona o si una persona está desempleada ($1$) o no ($0$) son variables aleatorias antes de observarlas.\n\n## Definición\n\n::: {.callout-note}\n## Definición: Variable aleatoria\nUna **variable aleatoria** es una función que asigna un número real a cada resultado del experimento:\n$$X: \\Omega \\longrightarrow \\mathbb{R}$$\n[@hansen-for-economist; @probability-statistics]\n:::\n\n. . .\n\nSi el resultado es un vector de números (por ejemplo, salario y experiencia de una misma persona) hablamos de un **vector aleatorio**.\n\n. . .\n\n::: {.callout-important}\n## Notación\n- $X$ (mayúscula) es la **variable aleatoria**: un objeto cuyo valor aún no conocemos.\n- $x$ (minúscula) es una **realización**: un número específico que $X$ puede tomar.\n\nAsí, $\\Pr(X = x)$ se lee \"la probabilidad de que la variable $X$ tome el valor $x$\".\n:::\n\n## Una variable aleatoria es una función\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nCada resultado de $\\Omega$ se envía a un punto de la recta real. La probabilidad \"viaja\" con la función: $\\Pr(X = 1) = \\Pr(\\{H\\})$ [@hansen-for-economist].\n\n# Variables aleatorias discretas {#discretas}\n\n## Soporte y función de masa de probabilidad\n\n::: {.callout-note}\n## Definición: Variable aleatoria discreta\n$X$ es **discreta** si existe un conjunto finito o infinito numerable $\\mathcal{X}$ tal que $\\Pr(X \\in \\mathcal{X}) = 1$. El menor conjunto con esta propiedad es el **soporte** de $X$: los valores que ocurren con probabilidad positiva [@hansen-for-economist].\n:::\n\n. . .\n\n::: {.callout-note}\n## Definición: Función de masa de probabilidad (PMF)\n$$\\pi(x) = \\Pr(X = x)$$\nAsigna a cada valor posible su probabilidad. Cumple $\\pi(x) \\geq 0$ y $\\sum_{x \\in \\mathcal{X}} \\pi(x) = 1$ [@hansen-for-economist; @probability-statistics].\n:::\n\n## Ejemplos de funciones de masa\n\n**Moneda con probabilidad $p$ de cara.** Soporte $\\{0, 1\\}$, con $\\pi(0) = 1 - p$ y $\\pi(1) = p$.\n\n. . .\n\n**Dado justo.** Soporte $\\{1, \\ldots, 6\\}$, con $\\pi(j) = 1/6$ para cada $j$.\n\n. . .\n\n**Un soporte infinito numerable.** Soporte $\\{0, 1, 2, \\ldots\\}$ con\n$$\\pi(k) = \\frac{e^{-1}}{k!}, \\qquad k = 0, 1, 2, \\ldots$$\n\nEs una función de masa válida porque $\\sum_{k=0}^{\\infty} 1/k! = e$. Es un caso particular de la distribución de Poisson, que veremos más adelante [@hansen-for-economist].\n\n. . .\n\n**Años de educación** (asalariados de EE.UU., 2009). La mayor probabilidad está en 12 años (cerca de 27%, secundaria completa) y la segunda en 16 años (cerca de 23%, título universitario) [@hansen-for-economist].\n\n## En R: graficar una función de masa\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nk  <- 0:5\npk <- dpois(k, lambda = 1)\nround(pk, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.368 0.368 0.184 0.061 0.015 0.003\n```\n\n\n:::\n\n```{.r .cell-code}\nbarplot(pk, names.arg = k,\n        col = \"#69000C\", border = NA,\n        xlab = \"k\",\n        ylab = \"Pr(X = k)\")\n```\n\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n. . .\n\nLa altura de cada barra es la probabilidad de ese valor. `dpois()` evalúa la función de masa de la Poisson; en R, las funciones que empiezan con `d` entregan masas o densidades.\n\n# Función de distribución {#cdf}\n\n## La función de distribución acumulada\n\n::: {.callout-note}\n## Definición: Función de distribución (CDF)\n$$F(x) = \\Pr(X \\leq x)$$\nEs la probabilidad de que $X$ tome un valor menor o igual que $x$ [@hansen-for-economist; @probability-statistics].\n:::\n\n. . .\n\nEscribimos $X \\sim F$ para decir que \"$X$ tiene distribución $F$\". Cuando hay varias variables, usamos subíndices: $F_X$, $F_Y$.\n\n. . .\n\nLa CDF tiene una gran ventaja: está definida para **cualquier** variable aleatoria, sea discreta, continua o mixta. Por eso es la forma más general de describir una distribución.\n\n## Propiedades de una CDF\n\n::: {.callout-important}\n## Teorema\nSi $F$ es una función de distribución, entonces [@hansen-for-economist]:\n\n1. $F(x)$ es no decreciente.\n2. $\\lim_{x \\to -\\infty} F(x) = 0$.\n3. $\\lim_{x \\to \\infty} F(x) = 1$.\n4. $F$ es continua por la derecha: $\\lim_{x \\downarrow x_0} F(x) = F(x_0)$.\n:::\n\n. . .\n\nLas propiedades 1 y 2 vienen del Axioma 1 (las probabilidades no son negativas) y la 3 del Axioma 2. La 4 es consecuencia de haber definido $F$ con \"$\\leq$\" y no con \"$<$\".\n\n. . .\n\nPara una variable **discreta**, la CDF es una [función escalonada]{.alert}: es constante entre los puntos del soporte y salta en cada uno de ellos una altura igual a $\\pi(x)$.\n\n## Probabilidades a partir de la CDF\n\nPara cualquier intervalo $(a, b]$:\n\n$$\\Pr(a < X \\leq b) = F(b) - F(a)$$\n\n. . .\n\n**Ejemplo: salarios por hora** (EE.UU., 2009). La CDF evaluada en algunos puntos es [@hansen-for-economist]:\n\n| $x$ | \\$10 | \\$20 | \\$30 | \\$40 | \\$50 |\n|---|---|---|---|---|---|\n| $F(x)$ | 0.14 | 0.54 | 0.78 | 0.89 | 0.94 |\n\n. . .\n\n- 54% de los salarios son menores o iguales a \\$20.\n- La probabilidad de que un salario esté entre \\$10 y \\$20 es $0.54 - 0.14 = 0.30$.\n- La probabilidad de que supere los \\$50 es $1 - 0.94 = 0.06$.\n\n# Variables aleatorias continuas y densidades {#continuas}\n\n## Variables aleatorias continuas\n\n::: {.callout-note}\n## Definición: Variable aleatoria continua\n$X$ es **continua** si su función de distribución $F(x)$ es continua [@hansen-for-economist].\n:::\n\n. . .\n\n**Ejemplo: Uniforme en $[0,1]$.**\n$$F(x) = \\begin{cases} 0 & x < 0 \\\\ x & 0 \\leq x \\leq 1 \\\\ 1 & x > 1 \\end{cases}$$\n\n. . .\n\n**Ejemplo: Exponencial.**\n$$F(x) = \\begin{cases} 0 & x < 0 \\\\ 1 - e^{-x} & x \\geq 0 \\end{cases}$$\n\nAmbas son continuas, parten en 0 y llegan a 1: cumplen las propiedades de una CDF.\n\n## Cada punto tiene probabilidad cero\n\nSi $F$ es continua, para cualquier número $x$ [@hansen-for-economist]:\n\n$$\\Pr(X = x) = \\lim_{\\epsilon \\to 0} \\Pr(x \\leq X \\leq x + \\epsilon) = \\lim_{\\epsilon \\to 0} \\left[F(x + \\epsilon) - F(x)\\right] = 0$$\n\n. . .\n\nEsto conecta con lo que vimos la clase pasada: **probabilidad cero no significa imposible**. Cada valor tiene probabilidad cero, pero la probabilidad de que $X$ tome *algún* valor es uno.\n\n. . .\n\nUna consecuencia práctica: para variables continuas da lo mismo usar desigualdades estrictas o no,\n\n$$\\Pr(a < X < b) = \\Pr(a \\leq X \\leq b) = F(b) - F(a)$$\n\n## La función de densidad\n\nLas variables continuas no tienen función de masa. Su análogo es la derivada de la CDF.\n\n. . .\n\n::: {.callout-note}\n## Definición: Función de densidad (PDF)\nCuando $F(x)$ es diferenciable, su **densidad** es\n$$f(x) = \\frac{d}{dx} F(x)$$\n[@hansen-for-economist; @probability-statistics]\n:::\n\n. . .\n\nUna función $f$ es una densidad si y solo si $f(x) \\geq 0$ para todo $x$ y $\\int_{-\\infty}^{\\infty} f(x)\\,dx = 1$. Por el teorema fundamental del cálculo,\n\n$$\\Pr(a \\leq X \\leq b) = \\int_a^b f(x)\\,dx$$\n\n[Las áreas bajo la densidad son probabilidades]{.alert}.\n\n## Cómo leer una densidad\n\n::: {.callout-warning}\n## Cuidado\n$f(x)$ **no** es una probabilidad. Puede ser mayor que 1 (por ejemplo, la uniforme en $[0, 0.5]$ tiene $f(x) = 2$). Lo que es una probabilidad es el área bajo $f$ en un intervalo.\n:::\n\n. . .\n\n**Ejemplo: salarios por hora** [@hansen-for-economist]:\n\n- Donde la densidad es alta, los valores de $X$ son relativamente más frecuentes.\n- El área entre \\$20 y \\$30 es 0.24: esa es la probabilidad de que un salario esté en ese rango.\n- La densidad tiene un único máximo cerca de \\$15. Ese punto se llama **moda**.\n- La cola derecha cae mucho más lento que la izquierda. Esta asimetría se llama **sesgo** (*skewness*) y es típica de los ingresos y la riqueza: hay una probabilidad pequeña, pero relevante, de salarios muy altos.\n\n## Ejemplos de densidades\n\n**Uniforme en $[0,1]$.** Derivando $F(x) = x$:\n$$f(x) = 1 \\quad \\text{para } 0 \\leq x \\leq 1, \\qquad 0 \\text{ en otro caso}$$\n\n. . .\n\n**Exponencial.** Derivando $F(x) = 1 - e^{-x}$:\n$$f(x) = e^{-x} \\quad \\text{para } x \\geq 0$$\n\n. . .\n\nCon ella podemos calcular, por ejemplo:\n$$\\Pr(1 \\leq X \\leq 2) = \\int_1^2 e^{-x}\\,dx = e^{-1} - e^{-2} \\approx 0.233$$\n\n## Cuantiles\n\n::: {.callout-note}\n## Definición: Cuantil\nPara una distribución continua, el **cuantil** $q(\\alpha)$ es el valor que deja una probabilidad $\\alpha$ a su izquierda:\n$$F(q(\\alpha)) = \\alpha \\qquad \\Longleftrightarrow \\qquad q(\\alpha) = F^{-1}(\\alpha)$$\n[@hansen-for-economist]\n:::\n\n. . .\n\n- La **mediana** es $q(0.5)$.\n- Los **cuartiles** son $q(0.25)$, $q(0.5)$ y $q(0.75)$. Los **deciles** son $q(0.1), \\ldots, q(0.9)$.\n- Expresados en porcentaje se llaman **percentiles**: el percentil 95 es $q(0.95)$.\n\n. . .\n\n**Ejemplo: salarios por hora.** Los cuartiles son \\$12.82, \\$18.88 y \\$28.35: la mitad de los asalariados gana \\$18.88 o menos por hora [@hansen-for-economist].\n\n## En R: `d`, `p`, `q` y `r`\n\nR usa el mismo prefijo para cada distribución: `d` (densidad o masa), `p` (CDF), `q` (cuantil) y `r` (simulación).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndexp(1)                  # densidad f(1) = e^(-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3678794\n```\n\n\n:::\n\n```{.r .cell-code}\npexp(2) - pexp(1)        # Pr(1 <= X <= 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2325442\n```\n\n\n:::\n\n```{.r .cell-code}\nqexp(c(0.5, 0.9))        # mediana y cuantil 0.9\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6931472 2.3025851\n```\n\n\n:::\n:::\n\n\n. . .\n\nLos cuantiles coinciden con la fórmula analítica $q(\\alpha) = -\\log(1 - \\alpha)$: la mediana es $\\approx 0.69$ y el cuantil 0.9 es $\\approx 2.30$ [@hansen-for-economist].\n\n# Transformaciones {#transformaciones}\n\n## Funciones de variables aleatorias\n\nSi $X$ es una variable aleatoria y $Y = g(X)$, entonces $Y$ **también es una variable aleatoria** [@hansen-for-economist; @probability-statistics].\n\n. . .\n\n**Caso discreto.** Los puntos del soporte se mueven y las probabilidades se conservan. Si dos puntos van al mismo valor, sus probabilidades se suman.\n\n**Ejemplo:** $X$ con soporte $\\{-1, 0, 1\\}$ e $Y = X^2$. Como $-1$ y $1$ van a $1$:\n$$\\Pr(Y = 0) = \\Pr(X = 0), \\qquad \\Pr(Y = 1) = \\Pr(X = -1) + \\Pr(X = 1)$$\n\n. . .\n\nEsto importa en economía porque trabajamos todo el tiempo con transformaciones: logaritmo del ingreso, ingreso al cuadrado, indicadores de pobreza, etc.\n\n## Transformaciones monótonas de variables continuas\n\n::: {.callout-note}\n## Teorema\nSi $X$ tiene densidad $f_X$ y $g$ es estrictamente monótona con inversa $g^{-1}$ diferenciable, entonces $Y = g(X)$ tiene densidad\n$$f_Y(y) = f_X\\big(g^{-1}(y)\\big)\\left|\\frac{d}{dy} g^{-1}(y)\\right|$$\n[@hansen-for-economist]\n:::\n\n. . .\n\nEl término $\\left|\\frac{d}{dy} g^{-1}(y)\\right|$ es el **jacobiano**: corrige por cuánto \"estira\" o \"comprime\" la transformación cada tramo de la recta.\n\n. . .\n\n**Ejemplo: log salarios.** Si $Y = \\log X$, entonces $f_Y(y) = f_X(e^y)\\,e^y$. La densidad de los log salarios es mucho más simétrica que la de los salarios en niveles [@hansen-for-economist]. Es una de las razones por las que en econometría solemos modelar $\\log(\\text{salario})$.\n\n## En R: de uniforme a exponencial\n\nUn resultado útil: si $U \\sim U[0,1]$, entonces $Y = -\\log U$ tiene distribución exponencial [@hansen-for-economist]. Comprobémoslo simulando:\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nset.seed(123)\nu <- runif(10000)\ny <- -log(u)\n\nhist(y, breaks = 50, freq = FALSE,\n     col = \"#69000C2E\", border = \"white\",\n     main = \"\", xlab = \"y\")\ncurve(dexp(x), add = TRUE,\n      col = \"#69000C\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n. . .\n\nEl histograma de los valores simulados coincide con la densidad exponencial teórica (línea roja).\n\n# Esperanza {#esperanza}\n\n## Esperanza de una variable discreta\n\n::: {.callout-note}\n## Definición: Esperanza\nPara una variable discreta con soporte $\\{\\tau_j\\}$ y masas $\\pi_j$, la **esperanza** (o valor esperado) de $X$ es\n$$\\mathbb{E}[X] = \\sum_{j} \\tau_j \\, \\pi_j$$\nsi la serie converge [@hansen-for-economist].\n:::\n\n. . .\n\nEs un **promedio ponderado** de los valores posibles, donde las ponderaciones son las probabilidades.\n\n. . .\n\n::: {.callout-important}\nAunque $X$ es aleatoria, $\\mathbb{E}[X]$ **no lo es**: es un número fijo, una característica de la distribución [@hansen-for-economist].\n:::\n\n## Ejemplos\n\n**Bernoulli.** $\\mathbb{E}[X] = 1 \\cdot p + 0 \\cdot (1-p) = p$\n\n. . .\n\n**Dado justo.** $\\mathbb{E}[X] = \\frac{1}{6}(1 + 2 + 3 + 4 + 5 + 6) = 3.5$\n\nNótese que 3.5 no es un valor que el dado pueda tomar: la esperanza no tiene por qué pertenecer al soporte.\n\n. . .\n\n**Años de educación** (EE.UU., 2009): $\\mathbb{E}[X] \\approx 14$ años [@hansen-for-economist].\n\n. . .\n\n**Interpretación física:** la esperanza es el [centro de masa]{.alert} de la distribución. Si pusiéramos las probabilidades como pesos sobre una tabla, la tabla quedaría en equilibrio al apoyarla en $\\mathbb{E}[X]$ [@hansen-for-economist].\n\n## Esperanza de una variable continua\n\n::: {.callout-note}\n## Definición\nSi $X$ tiene densidad $f(x)$,\n$$\\mathbb{E}[X] = \\int_{-\\infty}^{\\infty} x\\, f(x)\\,dx$$\ncuando la integral converge [@hansen-for-economist].\n:::\n\n. . .\n\n- **Uniforme en $[0,1]$:** $\\mathbb{E}[X] = \\int_0^1 x\\,dx = 1/2$\n- **Exponencial:** $\\mathbb{E}[X] = \\int_0^\\infty x e^{-x}\\,dx = 1$ (integrando por partes)\n\n. . .\n\n**Salarios por hora:** $\\mathbb{E}[X] = \\$23.92$, mientras que la mediana es \\$18.88 [@hansen-for-economist].\n\n::: {.callout-tip}\nEn distribuciones con sesgo a la derecha, como los ingresos, la media queda **por encima** de la mediana: los salarios muy altos \"tiran\" el promedio hacia arriba. Por eso muchas estadísticas oficiales de ingresos reportan la mediana.\n:::\n\n## Esperanza de transformaciones y linealidad\n\nLa esperanza de una función $g(X)$ se calcula con la distribución de $X$ [@hansen-for-economist]:\n\n$$\\mathbb{E}[g(X)] = \\sum_j g(\\tau_j)\\,\\pi_j \\qquad \\text{o} \\qquad \\mathbb{E}[g(X)] = \\int_{-\\infty}^{\\infty} g(x)\\,f(x)\\,dx$$\n\n. . .\n\n::: {.callout-important}\n## Teorema: Linealidad de la esperanza\nPara constantes $a$ y $b$:\n$$\\mathbb{E}[a + bX] = a + b\\,\\mathbb{E}[X]$$\n[@hansen-for-economist]\n:::\n\n. . .\n\n**Ejemplo:** si $X \\sim U[0,1]$, entonces $\\mathbb{E}[X^2] = \\int_0^1 x^2\\,dx = 1/3$. Observe que $\\mathbb{E}[X^2] = 1/3 \\neq (\\mathbb{E}[X])^2 = 1/4$: la linealidad **no** se extiende a funciones no lineales.\n\n## Desigualdad de Jensen\n\nPara funciones no lineales no podemos \"meter la esperanza adentro\", pero sí sabemos hacia dónde va el error si la función es convexa o cóncava.\n\n. . .\n\n::: {.callout-important}\n## Teorema: Desigualdad de Jensen\nSi $g$ es **convexa**: $\\quad g(\\mathbb{E}[X]) \\leq \\mathbb{E}[g(X)]$\n\nSi $g$ es **cóncava**: $\\quad \\mathbb{E}[g(X)] \\leq g(\\mathbb{E}[X])$\n\n[@hansen-for-economist]\n:::\n\n. . .\n\n**Ejemplo con salarios.** Como el logaritmo es cóncavo, $\\mathbb{E}[\\log X] \\leq \\log \\mathbb{E}[X]$. En los datos: $\\mathbb{E}[\\log(\\text{salario})] = 2.95$, mientras que $\\log(23.92) \\approx 3.17$ [@hansen-for-economist].\n\n. . .\n\nLa misma lógica explica la aversión al riesgo: con utilidad cóncava, la utilidad esperada de una lotería es menor que la utilidad de su valor esperado.\n\n## ¿Siempre existe la esperanza? (opcional)\n\nNo necesariamente. **La paradoja de San Petersburgo** [@hansen-for-economist]: se lanza una moneda hasta que sale cara. Si sale en el lanzamiento $k$, el pago es $X = 2^k$, con $\\Pr(X = 2^k) = 2^{-k}$.\n\n$$\\mathbb{E}[X] = \\sum_{k=1}^{\\infty} 2^k \\cdot 2^{-k} = \\sum_{k=1}^{\\infty} 1 = \\infty$$\n\n. . .\n\nA pesar de que la esperanza es infinita, casi nadie pagaría mucho por jugar. La \"paradoja\" desaparece al introducir una utilidad cóncava.\n\n. . .\n\nEn distribuciones continuas pasa lo mismo: la densidad $f(x) = x^{-2}$ para $x > 1$ (un caso de la Pareto) tiene esperanza infinita, y la distribución de Cauchy no tiene esperanza definida [@hansen-for-economist].\n\n# Varianza y momentos {#varianza}\n\n## Varianza y desviación estándar\n\n::: {.callout-note}\n## Definición\nLa **varianza** de $X$ es\n$$\\sigma^2 = \\text{var}(X) = \\mathbb{E}\\left[(X - \\mathbb{E}[X])^2\\right]$$\ny la **desviación estándar** es $\\sigma = \\sqrt{\\sigma^2}$ [@hansen-for-economist].\n:::\n\n. . .\n\n- La varianza mide la **dispersión** en torno a la media. Está en unidades al cuadrado; la desviación estándar vuelve a las unidades de $X$.\n- $\\sigma^2 \\geq 0$, y vale cero solo si $X$ es **degenerada** (constante con probabilidad 1).\n\n. . .\n\n::: {.callout-important}\n## Dos resultados útiles\n$$\\text{var}(X) = \\mathbb{E}[X^2] - (\\mathbb{E}[X])^2 \\qquad\\qquad \\text{var}(a + bX) = b^2\\,\\text{var}(X)$$\n[@hansen-for-economist]\n:::\n\nLa segunda implica que sumar una constante no cambia la varianza.\n\n## Ejemplos\n\n**Bernoulli.** $\\mathbb{E}[X^2] = p$, así que\n$$\\text{var}(X) = p - p^2 = p(1-p)$$\n\nLa varianza es máxima cuando $p = 1/2$: el caso más incierto.\n\n. . .\n\n**Uniforme en $[0,1]$.** $\\text{var}(X) = \\mathbb{E}[X^2] - (\\mathbb{E}[X])^2 = 1/3 - 1/4 = 1/12$\n\n. . .\n\n**Datos de EE.UU., 2009** [@hansen-for-economist]:\n\n| | Media | Varianza | Desv. estándar |\n|---|---|---|---|\n| Salario por hora | \\$24 | 429 | \\$20.7 |\n| Años de educación | 13.9 | 7.5 | 2.7 |\n\n## Momentos (opcional)\n\n::: {.callout-note}\n## Definición\n- El **momento** de orden $m$ es $\\mu'_m = \\mathbb{E}[X^m]$.\n- El **momento central** de orden $m$ es $\\mu_m = \\mathbb{E}[(X - \\mathbb{E}[X])^m]$.\n\n[@hansen-for-economist]\n:::\n\n. . .\n\n- La media es el primer momento y la varianza el segundo momento central.\n- El tercer momento central, normalizado por $\\sigma^3$, mide el **sesgo** (asimetría) de la distribución.\n- Los momentos serán la base del **método de momentos** en la clase 5: estimaremos parámetros igualando momentos poblacionales con sus análogos muestrales.\n\n# Distribuciones paramétricas {#parametricas}\n\n## Familias de distribuciones\n\n::: {.callout-note}\n## Definición: Distribución paramétrica\nUna **distribución paramétrica** $F(x \\mid \\theta)$ es una familia de distribuciones indexada por un **parámetro** $\\theta \\in \\Theta$. Para cada valor de $\\theta$ obtenemos una distribución distinta [@hansen-for-economist].\n:::\n\n. . .\n\nLos economistas las usan para construir **modelos teóricos**; los econometristas, para **modelos estadísticos**: suponemos que los datos vienen de una familia, pero no conocemos $\\theta$ y lo estimamos a partir de los datos [@hansen-for-economist].\n\n. . .\n\nEsta es la idea que organizará toda la unidad de estimación. Por ahora basta conocer algunas familias y entender cómo cambian con sus parámetros. No es necesario memorizarlas: se consultan cuando se necesitan [@hansen-for-economist].\n\n## Distribuciones discretas\n\n**Bernoulli$(p)$:** una variable con dos resultados, $\\Pr(X = 1) = p$. Modela, por ejemplo, si una persona está desempleada o no.\n\n. . .\n\n**Binomial$(n, p)$:** número de \"éxitos\" en $n$ ensayos Bernoulli independientes.\n$$\\pi(x) = \\binom{n}{x} p^x (1-p)^{n-x}, \\qquad x = 0, 1, \\ldots, n$$\n\nAquí reaparece el coeficiente binomial de la clase pasada.\n\n. . .\n\n**Poisson$(\\lambda)$:** conteos sin un máximo natural.\n$$\\pi(x) = \\frac{e^{-\\lambda}\\lambda^x}{x!}, \\qquad x = 0, 1, 2, \\ldots$$\n\nEn econometría se usa para datos de conteo (número de visitas al médico, de patentes, de hijos). Un solo parámetro $\\lambda$ determina a la vez la media y la varianza [@hansen-for-economist; @probability-statistics].\n\n## Distribuciones continuas\n\n**Uniforme $U[a, b]$:** todos los valores del intervalo son igualmente verosímiles.\n$$f(x) = \\frac{1}{b - a}, \\qquad a \\leq x \\leq b$$\n\n. . .\n\n**Exponencial$(\\lambda)$:** duraciones y tiempos de espera.\n$$f(x) = \\frac{1}{\\lambda} e^{-x/\\lambda}, \\qquad x \\geq 0$$\n\nEs muy usada en modelos teóricos por su simplicidad, pero poco en econometría aplicada [@hansen-for-economist].\n\n. . .\n\n**Normal $N(\\mu, \\sigma^2)$:** la distribución más usada en econometría.\n$$f(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} \\exp\\left(-\\frac{(x - \\mu)^2}{2\\sigma^2}\\right)$$\n\n## Resumen: medias y varianzas\n\n<table style=\"width:100%; font-size: 0.8em;\">\n<thead>\n<tr style=\"background-color: #69000C; color: white;\">\n<th style=\"padding: 8px;\">Distribución</th>\n<th style=\"padding: 8px;\">Soporte</th>\n<th style=\"padding: 8px;\">$\\mathbb{E}[X]$</th>\n<th style=\"padding: 8px;\">$\\text{var}(X)$</th>\n</tr>\n</thead>\n<tbody>\n<tr><td>Bernoulli$(p)$</td><td>$\\{0, 1\\}$</td><td>$p$</td><td>$p(1-p)$</td></tr>\n<tr><td>Binomial$(n, p)$</td><td>$\\{0, \\ldots, n\\}$</td><td>$np$</td><td>$np(1-p)$</td></tr>\n<tr><td>Poisson$(\\lambda)$</td><td>$\\{0, 1, 2, \\ldots\\}$</td><td>$\\lambda$</td><td>$\\lambda$</td></tr>\n<tr><td>Uniforme $U[a,b]$</td><td>$[a, b]$</td><td>$(a+b)/2$</td><td>$(b-a)^2/12$</td></tr>\n<tr><td>Exponencial$(\\lambda)$</td><td>$[0, \\infty)$</td><td>$\\lambda$</td><td>$\\lambda^2$</td></tr>\n<tr><td>Normal $N(\\mu, \\sigma^2)$</td><td>$\\mathbb{R}$</td><td>$\\mu$</td><td>$\\sigma^2$</td></tr>\n</tbody>\n</table>\n\n[@hansen-for-economist; @probability-statistics]\n\n::: {.callout-note}\nOjo con la parametrización de la exponencial: aquí $\\lambda$ es la **media** (como en Hansen). Otros textos, y la función `dexp()` de R, usan la **tasa** $1/\\lambda$.\n:::\n\n## En R: binomial y Poisson\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nbarplot(dbinom(0:10, size = 10, prob = 0.3), names.arg = 0:10, border = NA,\n        col = \"#69000C\", main = \"Binomial(10, 0.3)\")\nbarplot(dpois(0:10, lambda = 3), names.arg = 0:10, border = NA,\n        col = \"#69000C\", main = \"Poisson(3)\")\n```\n\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=864}\n:::\n:::\n\n\n## La distribución normal\n\nCuando $\\mu = 0$ y $\\sigma^2 = 1$ hablamos de la **normal estándar**. Su densidad se denota $\\phi(x)$ y su CDF $\\Phi(x)$ [@hansen-for-economist].\n\n. . .\n\n**Estandarización.** Si $X \\sim N(\\mu, \\sigma^2)$, entonces\n$$Z = \\frac{X - \\mu}{\\sigma} \\sim N(0, 1)$$\n\n$\\mu$ es un parámetro de **ubicación** y $\\sigma$ de **escala**: cambiar $\\mu$ desplaza la campana y cambiar $\\sigma$ la ensancha o la angosta.\n\n. . .\n\n**Una relación que usaremos más adelante:** si $Z \\sim N(0,1)$, entonces $Z^2$ tiene distribución **chi-cuadrado con 1 grado de libertad**, $\\chi^2_1$. Se obtiene aplicando la regla de transformaciones a $g(x) = x^2$ [@hansen-for-economist]. Junto con la $t$ y la $F$, la retomaremos al hacer inferencia.\n\n## En R: la regla 68–95–99.7\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(1) - pnorm(-1)     # Pr(-1 < Z < 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6826895\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(2) - pnorm(-2)     # Pr(-2 < Z < 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9544997\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(3) - pnorm(-3)     # Pr(-3 < Z < 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9973002\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975)             # cuantil 0.975\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\n. . .\n\nCerca de 68% de la probabilidad está a menos de una desviación estándar de la media, 95% a menos de dos y 99.7% a menos de tres. El cuantil 0.975, $\\approx 1.96$, aparecerá una y otra vez cuando construyamos intervalos de confianza.\n\n# Dos variables aleatorias {#bivariadas}\n\n## Distribución conjunta\n\nEn economía casi siempre nos interesa la relación entre variables: salario y educación, consumo e ingreso, precio y cantidad.\n\n. . .\n\n::: {.callout-note}\n## Definición\nUn par de **variables aleatorias bivariadas** $(X, Y)$ es una función de $\\Omega$ en $\\mathbb{R}^2$. Su **función de distribución conjunta** es\n$$F(x, y) = \\Pr(X \\leq x,\\; Y \\leq y)$$\n[@hansen-for-economist; @probability-statistics]\n:::\n\n. . .\n\nEn el caso discreto trabajamos con la **función de masa conjunta** $\\pi(x, y) = \\Pr(X = x, Y = y)$; en el continuo, con la **densidad conjunta** $f(x, y)$, y las probabilidades son volúmenes bajo esa superficie.\n\n## Ejemplo: la pizzería\n\nUna pizzería atiende estudiantes. Cada cliente compra una o dos porciones ($X$) y una o dos bebidas ($Y$). La función de masa conjunta es [@hansen-for-economist]:\n\n| | $Y = 1$ | $Y = 2$ | $\\Pr(X = x)$ |\n|---|---|---|---|\n| $X = 1$ | 0.4 | 0.1 | 0.5 |\n| $X = 2$ | 0.2 | 0.3 | 0.5 |\n| $\\Pr(Y = y)$ | 0.6 | 0.4 | 1 |\n\n. . .\n\nLas cuatro probabilidades del centro son no negativas y suman uno: es una función de masa válida. La última fila y la última columna son las **distribuciones marginales**.\n\n## Distribuciones marginales\n\n::: {.callout-note}\n## Definición\nLa **distribución marginal** de $X$ es la distribución de $X$ sola. Se obtiene \"sumando\" o \"integrando\" la otra variable [@hansen-for-economist]:\n$$\\pi_X(x) = \\sum_y \\pi(x, y) \\qquad\\qquad f_X(x) = \\int_{-\\infty}^{\\infty} f(x, y)\\,dy$$\n:::\n\n. . .\n\n**En la pizzería:**\n\n- $\\Pr(X = 1) = 0.4 + 0.1 = 0.5$: la mitad de los clientes compra una porción.\n- $\\Pr(Y = 1) = 0.4 + 0.2 = 0.6$: 60% compra una bebida.\n\n. . .\n\nEs la misma idea de la ley de probabilidad total de la clase pasada. La conjunta determina las marginales, pero **las marginales no determinan la conjunta**.\n\n## Distribución condicional\n\n::: {.callout-note}\n## Definición\nLa **distribución condicional** de $Y$ dado $X = x$ es la distribución de $Y$ en la subpoblación con $X = x$ [@hansen-for-economist]:\n$$\\pi_{Y|X}(y \\mid x) = \\frac{\\pi(x, y)}{\\pi_X(x)} \\qquad\\qquad f_{Y|X}(y \\mid x) = \\frac{f(x, y)}{f_X(x)}$$\n:::\n\n. . .\n\n**Ejemplo: salarios según educación** (EE.UU., 2009). Al comparar la distribución de salarios de quienes tienen 12, 16, 18 y 20 años de educación [@hansen-for-economist]:\n\n- Las distribuciones se desplazan a la derecha con cada nivel educativo.\n- También se vuelven **más dispersas**: los universitarios ganan más en promedio, pero sus salarios varían más.\n- Hay una zona amplia de superposición entre grupos.\n\n## Independencia de variables aleatorias\n\n::: {.callout-note}\n## Definición\n$X$ e $Y$ son **independientes**, $X \\perp\\!\\!\\!\\perp Y$, si para todo $(x, y)$\n$$F(x, y) = F_X(x)\\,F_Y(y)$$\nEquivalentemente, $\\pi(x, y) = \\pi_X(x)\\,\\pi_Y(y)$ o $f(x, y) = f_X(x)\\,f_Y(y)$ [@hansen-for-economist].\n:::\n\n. . .\n\nEs la definición de independencia de eventos de la clase pasada, aplicada a todos los eventos $\\{X \\leq x\\}$ y $\\{Y \\leq y\\}$. Si son independientes, la condicional es igual a la marginal: $f_{Y|X}(y \\mid x) = f_Y(y)$.\n\n. . .\n\n**En la pizzería:** $\\Pr(X = 1, Y = 1) = 0.4$, pero $\\Pr(X = 1)\\Pr(Y = 1) = 0.5 \\times 0.6 = 0.3$. Porciones y bebidas son **dependientes** [@hansen-for-economist].\n\n## Covarianza y correlación\n\n::: {.callout-note}\n## Definición\n$$\\text{cov}(X, Y) = \\mathbb{E}\\big[(X - \\mathbb{E}[X])(Y - \\mathbb{E}[Y])\\big] = \\mathbb{E}[XY] - \\mathbb{E}[X]\\,\\mathbb{E}[Y]$$\n$$\\text{corr}(X, Y) = \\frac{\\text{cov}(X, Y)}{\\sqrt{\\text{var}(X)\\,\\text{var}(Y)}}$$\n[@hansen-for-economist]\n:::\n\n. . .\n\n- La correlación está entre $-1$ y $1$ (por la desigualdad de Cauchy-Schwarz). Valores cerca de cero indican una relación **lineal** débil.\n- Para sumas: $\\text{var}(X + Y) = \\text{var}(X) + \\text{var}(Y) + 2\\,\\text{cov}(X, Y)$.\n\n. . .\n\n**En la pizzería:** $\\mathbb{E}[XY] = 2.2$, $\\mathbb{E}[X] = 1.5$ y $\\mathbb{E}[Y] = 1.4$, así que $\\text{cov}(X, Y) = 2.2 - 2.1 = 0.1$ y $\\text{corr}(X, Y) \\approx 0.41$.\n\n## No correlación $\\neq$ independencia\n\n::: {.callout-important}\n## Teorema\nSi $X$ e $Y$ son independientes (con varianzas finitas), entonces no están correlacionadas. **Lo contrario no es cierto** [@hansen-for-economist].\n:::\n\n. . .\n\n**Contraejemplo:** sea $X \\sim U[-1, 1]$ e $Y = X^2$. Como la distribución de $X$ es simétrica en torno a cero, $\\mathbb{E}[X] = 0$ y $\\mathbb{E}[X^3] = 0$, así que\n$$\\text{cov}(X, Y) = \\mathbb{E}[X^3] - \\mathbb{E}[X]\\,\\mathbb{E}[X^2] = 0$$\n\n. . .\n\nSin embargo, $Y$ está **completamente determinada** por $X$. La covarianza solo capta relaciones lineales; una relación en forma de U puede tener covarianza cero.\n\n## Esperanza condicional\n\n::: {.callout-note}\n## Definición\nLa **esperanza condicional** de $Y$ dado $X = x$ es la esperanza de la distribución condicional:\n$$m(x) = \\mathbb{E}[Y \\mid X = x] = \\sum_y y\\,\\pi_{Y|X}(y \\mid x) \\qquad \\text{o} \\qquad \\int y\\, f_{Y|X}(y \\mid x)\\,dy$$\n[@hansen-for-economist]\n:::\n\n. . .\n\nEs el valor promedio de $Y$ en la subpoblación con $X = x$.\n\n. . .\n\n**En la pizzería:** $\\mathbb{E}[Y \\mid X = 1] = 1.2$ y $\\mathbb{E}[Y \\mid X = 2] = 1.6$. Quienes compran dos porciones compran, en promedio, más bebidas.\n\n. . .\n\n**Salario promedio por hora según años de educación** (EE.UU., 2009) [@hansen-for-economist]:\n\n| Educación | 8 | 12 | 14 | 16 | 18 | 20 |\n|---|---|---|---|---|---|---|\n| $\\mathbb{E}[\\text{salario} \\mid \\text{educ}]$ | \\$11.75 | \\$17.61 | \\$21.49 | \\$30.12 | \\$35.16 | \\$51.76 |\n\n## La esperanza condicional y la regresión\n\nLa función $m(x) = \\mathbb{E}[Y \\mid X = x]$ es el objeto central de la econometría: la **regresión** busca justamente describir cómo cambia el promedio de $Y$ con $X$.\n\n. . .\n\n**Ejemplo: salario según experiencia.** El salario esperado es cerca de \\$16.50 sin experiencia, sube casi linealmente hasta unos \\$26 a los 20 años y luego baja a unos \\$21 a los 50 años: un perfil en forma de U invertida [@hansen-for-economist]. Por eso, más adelante incluiremos la experiencia al cuadrado en las regresiones de salarios.\n\n. . .\n\n::: {.callout-warning}\nIgual que en la clase pasada: $\\mathbb{E}[\\text{salario} \\mid \\text{educ}]$ describe cómo difiere el salario promedio **entre** grupos con distinta educación. No dice cuánto aumentaría el salario de una persona si estudiara un año más. Esa es una pregunta causal.\n:::\n\n## Ley de esperanzas iteradas\n\n$m(x)$ es un número para cada $x$. Pero si la evaluamos en la variable aleatoria $X$, obtenemos $\\mathbb{E}[Y \\mid X]$, que **es una variable aleatoria** (una transformación de $X$) [@hansen-for-economist].\n\n. . .\n\n::: {.callout-important}\n## Teorema: Ley de esperanzas iteradas\nSi $\\mathbb{E}|Y| < \\infty$, entonces\n$$\\mathbb{E}\\big[\\mathbb{E}[Y \\mid X]\\big] = \\mathbb{E}[Y]$$\n[@hansen-for-economist]\n:::\n\nEn palabras: **el promedio de los promedios por grupo es el promedio total**.\n\n. . .\n\n**En la pizzería:**\n$$\\mathbb{E}[Y] = 0.5 \\times 1.2 + 0.5 \\times 1.6 = 1.4 \\qquad \\checkmark$$\n\n## Varianza condicional (opcional)\n\nLa **varianza condicional** $\\text{var}(Y \\mid X = x)$ es la varianza de $Y$ en la subpoblación con $X = x$ [@hansen-for-economist].\n\n. . .\n\n::: {.callout-important}\n## Teorema: Descomposición de la varianza\n$$\\text{var}(Y) = \\underbrace{\\mathbb{E}\\big[\\text{var}(Y \\mid X)\\big]}_{\\text{dentro de los grupos}} + \\underbrace{\\text{var}\\big(\\mathbb{E}[Y \\mid X]\\big)}_{\\text{entre grupos}}$$\n[@hansen-for-economist]\n:::\n\n. . .\n\n**Salarios según educación:** la varianza del salario es 150 para quienes tienen secundaria completa, 573 para universitarios y 1646 para quienes tienen posgrado profesional o doctorado. Con más educación sube el salario promedio, pero también su dispersión [@hansen-for-economist]. Cuando la varianza condicional cambia con $X$ hablamos de **heterocedasticidad**, un concepto clave en la unidad de regresión.\n\n## En R: el ejemplo de la pizzería\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np <- matrix(c(0.4, 0.1,\n              0.2, 0.3), nrow = 2, byrow = TRUE,\n            dimnames = list(X = c(\"1\", \"2\"), Y = c(\"1\", \"2\")))\nx <- c(1, 2); y <- c(1, 2)\n\npX <- rowSums(p)                     # marginal de X\npY <- colSums(p)                     # marginal de Y\nEY_dado_X <- (p %*% y) / pX          # E[Y | X = x]\nEY_dado_X\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \nX   [,1]\n  1  1.2\n  2  1.6\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(pX * EY_dado_X)                  # ley de esperanzas iteradas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.4\n```\n\n\n:::\n:::\n\n\n## En R: el ejemplo de la pizzería\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nEX  <- sum(x * pX);  EY <- sum(y * pY)\nEXY <- sum(outer(x, y) * p)          # E[XY]\ncovXY <- EXY - EX * EY\nvarX  <- sum(x^2 * pX) - EX^2\nvarY  <- sum(y^2 * pY) - EY^2\n\nc(cov = covXY, corr = covXY / sqrt(varX * varY))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      cov      corr \n0.1000000 0.4082483 \n```\n\n\n:::\n:::\n\n\n. . .\n\nLos resultados coinciden con los cálculos a mano: $\\text{cov}(X, Y) = 0.1$ y $\\text{corr}(X, Y) \\approx 0.41$.\n\n## Resumen de la clase\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n**Conceptos clave:**\n\n- Variable aleatoria como función $\\Omega \\to \\mathbb{R}$\n- Función de masa, CDF y densidad\n- Cuantiles y mediana\n- Transformaciones\n- Esperanza, varianza y Jensen\n- Familias paramétricas\n- Conjunta, marginal y condicional\n- Covarianza, correlación e independencia\n- Esperanza condicional e iteradas\n\n:::\n::: {.column width=\"50%\"}\n\n**Próxima clase:**\n\n- Muestreo aleatorio\n- La media muestral como variable aleatoria\n- Ley de los grandes números\n- Teorema central del límite\n\n:::\n:::\n\n## Para revisar\n\n::: {.callout-tip}\n## Lecturas sugeridas\n- Hansen, *Probability and Statistics for Economists*, Capítulo 2 y secciones seleccionadas de los capítulos 3 (3.1–3.9, 3.12) y 4 (4.1–4.16).\n- DeGroot & Schervish, Capítulo 3 (3.1–3.6), Capítulo 4 (4.1–4.3, 4.6–4.7) y Capítulo 5 (5.2, 5.4, 5.6).\n:::\n\n## Referencias\n\n::: {#refs}\n:::\n",
    "supporting": [
      "slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}